syntax = "proto2";
//俱乐部协议

//俱乐部成员身份 1:主席  10:管理员  20:普通成员  （中间留空一些数字，方便以后增加其它身份）

//俱乐部id    <1000000:大厅,大厅的id就是玩家所在分组的id    1000000~: 私人创建的俱乐部

//俱乐部权限 1:成员管理权限 -> 处理加入申请；踢出成员；加入黑名单；移除黑名单  
//           2:俱乐部币管理权限 -> 处理成员增加和退还俱乐部币的申请；把俱乐部账户的俱乐部币转给成员；强制回收成员的俱乐部币
//           3:开桌管理权限 -> 开桌

message ClubS_Proto
{
    required int32 Main_CMD =1 						            [default = 263]; //主命令 (不可改)
    required int32 ClubSLogOnReq_CMD =2 			            [default = 2];   //登陆请求
	required int32 ClubSLogOnResp_CMD =3			            [default = 3];   //登陆回复
    required int32 ClubSSwitchReq_CMD =4 			            [default = 4];   //切换俱乐部请求
	required int32 ClubSSwitchResp_CMD =5			            [default = 5];   //切换俱乐部回复(失败才有)
    required int32 ClubSCreateReq_CMD =6 			            [default = 6];   //创建俱乐部请求
	required int32 ClubSCreateResp_CMD =7			            [default = 7];   //创建俱乐部回复
    required int32 ClubSSearchReq_CMD =8 			            [default = 8];   //搜索俱乐部请求
	required int32 ClubSSearchResp_CMD =9			            [default = 9];   //搜索俱乐部回复
    required int32 ClubSApplyReq_CMD =10 			            [default = 10];  //申请加入俱乐部请求
	required int32 ClubSApplyResp_CMD =11			            [default = 11];  //申请加入俱乐部回复
    required int32 ClubSChangeInfoReq_CMD =12 	                [default = 12];  //修改俱乐部信息请求(主席)
	required int32 ClubSChangeInfoResp_CMD =13	                [default = 13];  //修改俱乐部信息回复(主席)
    required int32 ClubSMembersReq_CMD =14 	                    [default = 14];  //俱乐部成员请求
	required int32 ClubSMembersResp_CMD =15	                    [default = 15];  //俱乐部成员回复
    required int32 ClubSSearchMemberReq_CMD =16                 [default = 16];  //搜索俱乐部成员请求
    required int32 ClubSSearchMemberResp_CMD =17                [default = 17];  //搜索俱乐部成员返回
    required int32 ClubSOperateReq_CMD =18                      [default = 18];  //管理员操作请求(主席,管理员)
    required int32 ClubSOperateResp_CMD =19                     [default = 19];  //管理员操作返回(主席,管理员)
    required int32 ClubSTransferClubGoldReq_CMD =20             [default = 20];  //个人俱乐部币增加退还请求
	required int32 ClubSTransferClubGoldResp_CMD =21            [default = 21];  //个人俱乐部币增加退还回复
    required int32 ClubSTransferRecordReq_CMD =22               [default = 22];  //个人俱乐部币流水记录请求
	required int32 ClubSTransferRecordResp_CMD =23              [default = 23];  //个人俱乐部币流水记录回复
    required int32 ClubSPaiJuRecordReq_CMD =24                  [default = 24];  //俱乐部个人历史牌局请求
    required int32 ClubSPaiJuRecordResp_CMD =25                 [default = 25];  //俱乐部个人历史牌局返回
    required int32 ClubSContribRecordReq_CMD =26                [default = 26];  //俱乐部个人贡献请求(俱乐部收益请求)
    required int32 ClubSContribRecordResp_CMD =27               [default = 27];  //俱乐部个人贡献返回(俱乐部收益请求)
    required int32 ClubSBlacklistReq_CMD =28 	                [default = 28];  //俱乐部黑名单请求
	required int32 ClubSBlacklistResp_CMD =29	                [default = 29];  //俱乐部黑名单回复
    required int32 ClubSBlacklistMgrReq_CMD =30                 [default = 30];  //黑名单管理操作请求(主席,管理员)
    required int32 ClubSBlacklistMgrResp_CMD =31                [default = 31];  //黑名单管理操作返回(主席,管理员)
    required int32 ClubSBlacklistSearchReq_CMD =32              [default = 32];  //黑名单玩家搜索请求
    required int32 ClubSBlacklistSearchResp_CMD =33             [default = 33];  //黑名单玩家搜索返回
    required int32 ClubSTableRecordReq_CMD =34                  [default = 34];  //俱乐部牌桌记录请求
    required int32 ClubSTableRecordResp_CMD =35                 [default = 35];  //俱乐部牌桌记录返回
    required int32 ClubSTableUserReq_CMD =36                    [default = 36];  //俱乐部牌桌参与玩家请求
    required int32 ClubSTableUserResp_CMD =37                   [default = 37];  //俱乐部牌桌参与玩家返回
    required int32 ClubSMemberInfoReq_CMD =38                   [default = 38];  //俱乐部成员信息请求
    required int32 ClubSMemberInfoResp_CMD =39                  [default = 39];  //俱乐部成员信息返回
    required int32 ClubSAdminListReq_CMD =40                    [default = 40];  //俱乐部管理员列表请求(主席)
    required int32 ClubSAdminListResp_CMD =41                   [default = 41];  //俱乐部管理员列表返回(主席)
    required int32 ClubSAdminMgrReq_CMD =42                     [default = 42];  //俱乐部增加删除管理员请求(主席)
    required int32 ClubSAdminMgrResp_CMD =43                    [default = 43];  //俱乐部增加删除管理员返回(主席)
    required int32 ClubSChangeAdminPowerReq_CMD =44             [default = 44];  //修改管理员权限请求(主席)
    required int32 ClubSChangeAdminPowerResp_CMD =45            [default = 45];  //修改管理员权限返回(主席)
    required int32 ClubSGoldChangeRecordReq_CMD =46             [default = 46];  //俱乐部账户的俱乐部币流水请求
    required int32 ClubSGoldChangeRecordResp_CMD =47            [default = 47];  //俱乐部账户的俱乐部币流水返回
    required int32 ClubSApplyListReq_CMD =48                    [default = 48];  //俱乐部申请列表请求(主席,管理员)
    required int32 ClubSApplyListResp_CMD =49                   [default = 49];  //俱乐部申请列表返回(主席,管理员)
    required int32 ClubSApplyHandleReq_CMD =50                  [default = 50];  //俱乐部申请处理请求(主席,管理员)
    required int32 ClubSApplyHandleResp_CMD =51                 [default = 51];  //俱乐部申请处理返回(主席,管理员)
    required int32 ClubSInviteUserReq_CMD =52                   [default = 52];  //邀请用户请求(主席,管理员)
    required int32 ClubSInviteUserResp_CMD =53                  [default = 53];  //邀请用户返回(主席,管理员)
    required int32 ClubSSearchUserReq_CMD =54                   [default = 54];  //搜索用户请求(在所有注册玩家里搜索)
    required int32 ClubSSearchUserResp_CMD =55                  [default = 55];  //搜索用户返回
    required int32 ClubSUserInfoReq_CMD =56                     [default = 56];  //玩家个人信息请求
    required int32 ClubSUserInfoResp_CMD =57                    [default = 57];  //玩家个人信息返回
    required int32 ClubSChangeUserInfoReq_CMD =58               [default = 58];  //修改玩家个人信息请求
    required int32 ClubSChangeUserInfoResp_CMD =59              [default = 59];  //修改玩家个人信息返回
    required int32 ClubSPaiPuReq_CMD =60                        [default = 60];  //牌谱请求
    required int32 ClubSPaiPuResp_CMD =61                       [default = 61];  //牌谱返回
    required int32 ClubSOpratePaiPuReq_CMD =62                  [default = 62];  //操作牌谱请求
    required int32 ClubSOpratePaiPuResp_CMD =63                 [default = 63];  //操作牌谱返回
    required int32 ClubSPlaybackDataReq_CMD =64                 [default = 64];  //回放数据请求
    required int32 ClubSPlaybackDataResp_CMD =65                [default = 65];  //回放数据返回
    required int32 ClubSUserNoticeReq_CMD =66                   [default = 66];  //个人通知请求
    required int32 ClubSUserNoticeResp_CMD =67                  [default = 67];  //个人通知返回
    required int32 ClubSUserNoticeHandleReq_CMD =68             [default = 68];  //处理个人通知请求
    required int32 ClubSUserNoticeHandleResp_CMD =69            [default = 69];  //处理个人通知返回
    required int32 ClubSGetUserClubListReq_CMD =70              [default = 70];  //获取玩家的俱乐部列表请求
    required int32 ClubSGetUserClubListResp_CMD =71             [default = 71];  //获取玩家的俱乐部列表返回
    required int32 ClubSSceneChangeNotify_CMD =72               [default = 72];  //俱乐部场景信息改变通知
    required int32 ClubSUserInfoChangeNotify_CMD =73            [default = 73];  //俱乐部玩家信息改变通知
    required int32 ClubSKickOutNotify_CMD =74                   [default = 74];  //踢出俱乐部通知
    required int32 ClubSUserMsgNotify_CMD =75                   [default = 75];  //玩家消息通知(非俱乐部)
    required int32 ClubSGetGameParamsReq_CMD =76                [default = 76];  //获取后台配置请求
    required int32 ClubSGetGameParamsResp_CMD =77               [default = 77];  //获取后台配置返回
    required int32 ClubSOpenTableReq_CMD =78                    [default = 78];  //俱乐部开桌请求
    required int32 ClubSOpenTableResp_CMD =79                   [default = 79];  //俱乐部开桌返回
    required int32 ClubSOpenTableNotify_CMD =80                 [default = 80];  //俱乐部开桌通知
    required int32 ClubSCloseTableReq_CMD =81                   [default = 81];  //俱乐部关桌请求
    required int32 ClubSCloseTableResp_CMD =82                  [default = 82];  //俱乐部关桌返回
    required int32 ClubSCloseTableNotify_CMD =83                [default = 83];  //俱乐部关桌通知
    required int32 ClubSGetTableListReq_CMD =84                 [default = 84];  //俱乐部牌桌列表请求
    required int32 ClubSGetTableListResp_CMD =85                [default = 85];  //俱乐部牌桌列表返回
    required int32 ClubSTableInfoNotify_CMD =86                 [default = 86];  //俱乐部牌桌信息变化通知
    required int32 ClubSCloseNotify_CMD =87                     [default = 87];  //俱乐部关闭通知
    required int32 ClubSMaintenanceNotify_CMD =88               [default = 88];  //服务器维护通知(需要重新登录俱乐部)
    required int32 ClubSGetApplyListReq_CMD =89                 [default = 89];  //玩家申请记录请求（玩家个人）
    required int32 ClubSGetApplyListResp_CMD =90                [default = 90];  //玩家申请记录返回（玩家个人）
    required int32 ClubSUserApplyOpReq_CMD =91                  [default = 91];  //玩家申请处理请求（玩家个人）
    required int32 ClubSUserApplyOpResp_CMD =92                 [default = 92];  //玩家申请处理返回（玩家个人）
    required int32 ClubSChangeLoginPassWardReq_CMD =93          [default = 93];  //修改登录密码请求
    required int32 ClubSChangeLoginPassWardResp_CMD =94         [default = 94];  //修改登录密码返回
    required int32 ClubSUserRedDotReq_CMD =95                   [default = 95];  //玩家红点数据请求
    required int32 ClubSUserRedDotResp_CMD =96                  [default = 96];  //玩家红点信息返回
    required int32 ClubSGetTablePaiJuIdReq_CMD =97              [default = 97];  //获取牌桌的牌局id请求
    required int32 ClubSGetTablePaiJuIdResp_CMD =98             [default = 98];  //获取牌桌的牌局id返回
    required int32 ClubSSetSafePassWardOpenReq_CMD =99          [default = 99];  //设置安全密码开启关闭请求
    required int32 ClubSSetSafePassWardOpenResp_CMD =100        [default = 100]; //设置安全密码开启关闭返回
    required int32 ClubSGetClubConfigReq_CMD =101               [default = 101]; //获取俱乐部相关配置请求
    required int32 ClubSGetClubConfigResp_CMD =102              [default = 102]; //获取俱乐部相关配置返回
    required int32 ClubSGetClubConfigNotify_CMD =103            [default = 103]; //俱乐部相关配置变化通知
    required int32 ClubSSendCodeReq_CMD =104                    [default = 104]; //发送短信验证码请求
    required int32 ClubSSendCodeResp_CMD =105                   [default = 105]; //发送短信验证码返回
    required int32 ClubSCodeCheckReq_CMD =106                   [default = 106]; //短信验证码校验请求
    required int32 ClubSCodeCheckResp_CMD =107                  [default = 107]; //短信验证码校验返回
    required int32 ClubSSafePassWardCheckReq_CMD =108           [default = 108]; //安全密码校验请求
    required int32 ClubSSafePassWardCheckResp_CMD =109          [default = 109]; //安全密码校验返回
    required int32 ClubSNeedCheckSafePassWardReq_CMD =110       [default = 110]; //是否需要安全码校验请求
    required int32 ClubSNeedCheckSafePassWardResp_CMD =111      [default = 111]; //是否需要安全码校验返回
    required int32 ClubSPersonInfoNotify_CMD =112               [default = 112]; //玩家个人信息通知


    required int32 ClubSGetPersonTableRecordReq_CMD=113         [default = 113]; //获取玩家个人牌桌记录请求
    required int32 ClubSGetPersonTableRecordRsp_CMD=114         [default = 114]; //获取玩家个人牌桌记录返回

    required int32 ClubSGetTableDetailReq_CMD=115               [default = 115]; //获取牌桌详细记录请求
    required int32 ClubSGetTableDetailRsp_CMD=116               [default = 116]; //获取牌桌详细记录返回

    required int32 ClubSGetTablePaiPuReq_CMD=117                [default = 117]; //获取牌桌牌谱请求
    required int32 ClubSGetTablePaiPuRsp_CMD=118                [default = 118]; //获取牌桌牌谱返回

    required int32 ClubSGetTableInsuranceReq_CMD=119            [default = 119]; //获取牌桌保险明细请求
    required int32 ClubSGetTableInsuranceRsp_CMD=120            [default = 120]; //获取牌桌保险明细返回

    required int32 ClubSGetTableUserListReq_CMD=121             [default = 121]; //获取牌桌玩家列表请求
    required int32 ClubSGetTableUserListRsp_CMD=122             [default = 122]; //获取牌桌玩家列表返回
    
    required int32 ClubSWebKickOutNotify_CMD=123                [default = 123]; //后台设置黑名单踢出通知(需要回到登录界面)

    required int32 ClubSGetStoreCfgReq_CMD = 200                [default = 200];  //请求商城配置
    required int32 ClubSGetStoreCfgRep_CMD =201                 [default = 201];  //请求商城配置 返回
    required int32 ClubSBuyGoodsReq_CMD = 202                   [default = 202];  //请求购买商品
    required int32 ClubSBuyGoodsRep_CMD = 203                   [default = 203];  //购买商品返回
    required int32 ClubSPayResultRep_CMD = 204                  [default = 204];  //支付结果返回

    required int32 ClubSInputRedeemCodeReq_CMD = 210            [default = 210];  // 输入兑换码请求
    required int32 ClubSInputRedeemCodeRsp_CMD = 211            [default = 211];  // 输入兑换码返回

    required int32 ClubSGetPersonTableRecord2Req_CMD=215         [default = 215]; //获取玩家个人牌桌记录2请求(大厅 永久牌桌)
    required int32 ClubSGetPersonTableRecord2Rsp_CMD=216         [default = 216]; //获取玩家个人牌桌记录2返回(大厅 永久牌桌)

    required int32 ClubSGetTableDetail2Req_CMD=217               [default = 217]; //获取牌桌详细记录2请求(大厅 永久牌桌)
    required int32 ClubSGetTableDetail2Rsp_CMD=218               [default = 218]; //获取牌桌详细记录2返回(大厅 永久牌桌)

    required int32 ClubSGetTableUserList2Req_CMD=219             [default = 219]; //获取牌桌玩家列表2请求(大厅 永久牌桌)
    required int32 ClubSGetTableUserList2Rsp_CMD=220             [default = 220]; //获取牌桌玩家列表2返回(大厅 永久牌桌)

    required int32 ClubSGetTablePaiPu2Req_CMD=221                [default = 221]; //获取牌桌牌谱2请求(大厅 永久牌桌)
    required int32 ClubSGetTablePaiPu2Rsp_CMD=222                [default = 222]; //获取牌桌牌谱2返回(大厅 永久牌桌)

    required int32 ClubSGetTableInsurance2Req_CMD=223            [default = 223]; //获取牌桌保险明细2请求(大厅 永久牌桌)
    required int32 ClubSGetTableInsurance2Rsp_CMD=224            [default = 224]; //获取牌桌保险明细2返回(大厅 永久牌桌)

    required int32 ClubSGetPaijuDetailReq_CMD=225            	 [default = 225]; //牌局明细查询请求(大厅:抢庄牛)
    required int32 ClubSGetPaijuDetailRsp_CMD=226            	 [default = 226]; //牌局明细查询返回(大厅:抢庄牛)
    required int32 ClubSPayInfoReq_CMD=230                  	 [default = 230]; // 请求充值信息
    required int32 ClubSPayInfoRep_CMD=231                  	 [default = 231]; // 请求充值信息返回
    required int32 ClubSWithDrawGoldRep_CMD=232                  [default = 232]; // 用户提现信息返回

    required int32 ClubSAdvertiseMentGoldRep_CMD=233             [default = 233]; // 俱乐部广告奖励金请求
    required int32 ClubSAdvertiseMentGoldRsp_CMD=234             [default = 234]; // 俱乐部广告奖励金返回

    required int32 ClubSUserMWStringReq_CMD=235                   [default = 235]; //明文密码请求
    required int32 ClubSUserMWStringRsp_CMD=236                   [default = 236]; //明文密码返回

    required int32 ClubsFileConfigReq_CMD=237                          [default = 237]; //前端用文件编码请求
    required int32 ClubsFileConfigRsp_CMD=238                          [default = 238]; //前端用文件编码返回

    // required int32 ClubTransferWayReq_CMD=239                       [default = 239]; //转账方式请求
    // required int32 ClubTransferWayRsp_CMD=240                       [default = 240]; //转账方式返回

    // required int32 ClubRechargeWithdrawalReq_CMD=241                [default = 241]; //充值或提现请求
    // required int32 ClubRechargeWithdrawalRsp_CMD=242                [default = 242]; //充值或提现返回
  
    required int32 ClubActivityRewardHandleReq_CMD=245                 [default = 245]; //活动奖励操作请求
    required int32 ClubActivityRewardHandleRsp_CMD=246                 [default = 246]; //活动奖励操作返回

}

//登陆请求 ClubSLogOnReq_CMD
message ClubSLogOnReq
{   
    required int32 nUserId =1   [default = 0];
    required int32 nClubId = 2  [default = 0]; //俱乐部id  发0就是登录大厅 没有俱乐部和大厅的时候，发-1
    optional string nInviteCode = 3 [default = ""]; //邀请码
}

//登陆回复 ClubSLogOnResp_CMD
message ClubSLogOnResp
{
    required int32 nRlt = 1;    //0:成功 1:玩家id不正确 2:没有找到俱乐部(大厅) 3:玩家分组与俱乐部分组不一致 4:在其它俱乐部中 5:不是该俱乐部成员 6:维护中 7:账号被封 8:IP被封 9：GPS被封
    required string sErrStr = 2; //错误信息
    optional ClubSScene tScence = 3; //俱乐部场景数据，登录成功才有
    optional int32 ifBinging = 4; //是否为绑定用户 1为是 0为否
    optional int32 nflag = 5; //是否能看见邀请码相关内容开关 0：关 1：开
}

//切换俱乐部请求 ClubSSwitchReq_CMD
message ClubSSwitchReq
{
    required int32 nUserId =1      [default = 0];
    required int32 nNewClubId = 2  [default = 0]; //要去的俱乐部id
}

//切换俱乐部回复 ClubSSwitchResp_CMD
message ClubSSwitchResp
{
    required int32 nRlt = 1;    //1:没有找到玩家 2:离开俱乐部失败 3:请求过于频繁，等待上一个请求结束
    required string sErrStr = 2; //错误信息
    required int32 nNewClubId = 3; //要去的俱乐部id
    required int32 nNowClubId = 4; //现在的俱乐部id
}

//俱乐部场景数据
message ClubSScene
{   
    required int32 nClubId = 1;           //俱乐部id
    required string sClubName = 2;        //俱乐部名称(Base64编码)
    required double nClubGold = 3;        //俱乐部资产(俱乐部币)
    required ClubSUser tMyself = 4;       //个人信息
    required double nIncome = 5;          //总收益(俱乐部币)
    required double nTodayIncome = 6;     //今日收益(俱乐部币)
    required int32 nMaxUserCnt = 7;       //俱乐部人数上限
    required int32 nClubTax = 8;          //俱乐部桌服务费分成(在抽水中的占比),需要除以1000,如分成=95%,nClubTax=950
    required int32 nInsuranceTax = 9;     //俱乐部桌保险分成(在保险中的占比),需要除以1000,如分成=95%,nInsuranceTax=950
    optional int32 nApplyJionCnt= 10;     //加入俱乐部申请数目(有成员管理权限的用户才有)
    optional int32 nApplyAddGoldCnt= 11;  //增加俱乐部币申请数目(有俱乐部币管理权限的用户才有)
    optional int32 nApplyCutGoldCnt= 12;  //增加俱乐部币申请数目(有俱乐部币管理权限的用户才有)
    optional int32 nCanSearch = 13;       //是否允许搜索 0:允许 1:不允许
    optional int32 nCanApply = 14;        //是否允许申请加入 0:允许 1:不允许
    optional ClubSUser tMasterInfo = 15;  //主席基本信息(增加 减少金币会用到)
    required bool IsUseGold = 16;         //俱乐部是否使用金币
    required bool IsUserClubGold = 17;    //俱乐部是否使用俱乐部币
    required double nGold = 18;	          //俱乐部资产(金币)
	required double nGoldIncome = 19;	  //总收益(金币)
    required double nGoldTodayIncome = 20;//今日收益(金币)
    
    optional string sClubConfig = 21;        //俱乐部配置: json 
    /*
        IsManchu --牌桌满人开关 
        arrOpenGameId ={}  -- 开放游戏id
    */
    optional int32 nAdertisementGoldLeftCnt = 22;        //看广告赠送金币今日剩余次数（登录大厅俱乐部时才有）
}

//俱乐部用户信息(个人)
message ClubSUser
{   
    required int32 nUserId=1;				//玩家id
	required string sFaceId=2;				//url
	required string sName=3;				//昵称
	required int32 nSex=4;	    			//性别 0:男 1:女
    required int32 nClubId=5;               //俱乐部id
    required string sShopAcc=6;			    //第三方id
    optional int32 nIdentify=7;             //身份  1:主席  10:管理员  20:普通成员
	optional double nContribution=8;        //累计贡献(俱乐部币)
    optional string sPower=9;				//权限 json格式 [{nPowerType,isOpen},...] 
                                            // nPowerType权限类型:1:成员管理权限 2:俱乐部币管理权限 3:开桌管理权限.  
                                            // isOpen是否开启 true:开启  false:关闭
	optional double nGold=10;				//金币
	optional double nClubGold=11;			//俱乐部币
    optional int32 nWeekCount=12;           //本周局数
    optional double nGoldContribution=13;   //累计贡献(金币)
	optional string nCreateTime=14;         //加入时间
}

//创建俱乐部请求 ClubSCreateReq_CMD
message ClubSCreateReq
{
    required string sClubName = 1  [default = ""];  //俱乐部名称(Base64编码)
    required int32 nCanSearch = 2  [default = 0];  //是否允许搜索 0:允许 1:不允许
    required int32 nCanApply = 3   [default = 0];  //是否允许申请加入 0:允许 1:不允许
    required string sPassWord = 4  [default = ""]; //库存密码(Base64编码)
}

//创建俱乐部回复 ClubSCreateResp_CMD
message ClubSCreateResp
{
    required int32 nRlt = 1;    //0:成功 1:参数错误 2:库存密码不符合要求 3:俱乐部已存在 4:名字超长 5:含有特殊字符 6:含有敏感词 7:创建俱乐部达到上限 99:数据库操作失败 
    required string sErrStr = 2; //错误信息
    optional int32 nClubId = 3; //俱乐部id，成功才有
}

//搜索俱乐部请求 ClubSSearchReq_CMD
message ClubSSearchReq
{
    required string str = 1 [default = ""]; //检索字符串(base64编码)
}

//搜索俱乐部回复 ClubSSearchResp_CMD
message ClubSSearchResp
{
    message ClubItem
    {
        required int32 nClubId = 1;  //俱乐部id
        required string sClubName = 2;  //俱乐部名称(Base64编码)
        required string sMasterName = 3; //主席昵称
        required int32 nUserCnt = 4; //目前成员个数
        required int32 nMaxUserCnt = 5; //最大成员个数
        required int32 nStatus = 6; //状态 0:未申请 1:已申请  2:已加入
        required int32 nMaster = 7; //主席id
    }
    repeated ClubItem arrItem = 1; //搜索结果列表
    required int32 nPage = 2; //第几页
    required int32 nAllPage = 3; //总页数
}

//申请加入俱乐部请求 ClubSApplyReq_CMD
message ClubSApplyReq
{
    required int32 nClubId = 1  [default = 0]; //俱乐部id
}

//申请加入俱乐部回复 ClubSApplyResp_CMD
message ClubSApplyResp
{
    required int32 nRlt = 1;    //0:成功 1:参数错误 2:俱乐部不存在 3:已申请 4:俱乐部设置不能申请 5:已在俱乐部中 6:玩家与俱乐部不是同一个分组 7:在黑名单中 8:申请数目达到上限 99:数据库操作失败
    required string sErrStr = 2; //错误信息
}

//修改俱乐部信息请求(主席) ClubSChangeInfoReq_CMD
// string sClubName = 2;          //俱乐部名称(Base64编码)
// int32 nCanSearch = 3;          //是否允许搜索 0:允许 1:不允许
// int32 nCanApply = 4;           //是否允许申请加入 0:允许 1:不允许
// sOldPassWord = 5;       //库存密码(旧)
// sNewPassWord = 6;       //库存密码(新)
message ClubSChangeInfoReq
{
    message Item {
        required string sKey = 1;
        required string sVal = 2;
    }
    required int32 nClubId = 1 [default=0]; //俱乐部id
    repeated Item arrItem = 2;
}

//修改俱乐部信息回复(主席) ClubSChangeInfoResp_CMD
message ClubSChangeInfoResp
{   
    required int32 nClubId = 1;       //俱乐部id
    repeated ClubSRltItem arrRlt = 2; //修改结果
    required int32 nRlt = 3; //总的修改结果,所有项都修改成功才算成功，其中一项失败都算失败 0:成功 1:失败
}

message ClubSRltItem
{
    required int32 nRlt = 1;    //0:成功 1:没有权限,2:俱乐部名字已存在 3:参数错误 4:旧的库存密码不正确 5:新旧值相同 6:俱乐部不存在 7:名字超长 8:含有特殊字符 9:含有敏感词 99:数据库操作失败
    required string sKey = 3;  //修改的项 sClubName,nCanSearch,nCanApply,sPassWord
}

//俱乐部成员请求 ClubSMembersReq_CMD
message ClubSMembersReq
{
    required int32 nClubId = 1    [default = 0]; //俱乐部id
	required int32 nCnt=2 		  [default = 10];//本页的记录数目
	required int32 nPage=3 		  [default = 1]; //第几页 nPage>=1
}

//俱乐部成员回复 ClubSMembersResp_CMD
message ClubSMembersResp
{   
    repeated ClubSUser arrUser = 1; //俱乐部成员数组
    required int32 nPage = 2; //第几页
    required int32 nUserCnt = 3; //目前成员数
    required int32 nMaxUserCnt = 4; //成员数上限
}

//搜索俱乐部成员请求 ClubSSearchMemberReq_CMD
message ClubSSearchMemberReq
{   
    required int32 nClubId = 1  [default = 0];  //俱乐部id
    required string str = 2     [default = ""]; //检索字符串(base64加密)
}

//搜索俱乐部成员返回 ClubSSearchMemberResp_CMD
message ClubSSearchMemberResp
{
    repeated ClubSUser arrUser = 1; //俱乐部成员数组 
    required int32 nPage = 2; //第几页
    required int32 nAllPage = 3; //总页数
}

//管理员操作请求 ClubSOperateReq_CMD
message ClubSOperateReq
{
    required int32 nClubId=1      [default = 0]; //俱乐部id
    required int32 nTUserId=2      [default = 0]; //被操作的玩家UserId
    required int32 nType=3        [default = 0]; //操作类型 1:增加俱乐部币 2:回收俱乐部币 3:踢出俱乐部
    optional double nChange=4     [default = 0]; //增加or回收的俱乐部币(nType=1和nType=2要传)
    optional string sPassWord=5   [default = ""];//库存密码(nType=1和nType=2要传)(Base64编码)
}

//管理员操作返回 ClubSOperateResp_CMD
message ClubSOperateResp
{
    required int32 nRlt = 1;     //0:成功 1:没有登录俱乐部 2:被操作的玩家不是俱乐部成员 3:权限不足 4:参数错误 
                                 //5:上一个操作未完成 6:俱乐部账户的俱乐部币不足 7:被操作的玩家在游戏中,稍后为你处理 
                                 //8:库存密码不正确 9:俱乐部不存在 10:身份不够 11:玩家俱乐部币不足 12:修改俱乐部币失败
                                 //13:被操作者是其它管理员 14:被操作者是主席 15:数据库操作失败 16:不能踢出自己
    required string sErrStr = 2; //错误信息
    required int32 nTUserId=3;   //被操作的玩家UserId
    required int32 nType=4;      //操作类型 1:增加俱乐部币 2:回收俱乐部币 3:踢出俱乐部
    required int32 nClubId=5;    //俱乐部id
}

//个人俱乐部币增加退还请求 ClubSTransferClubGoldReq_CMD
message ClubSTransferClubGoldReq
{
    required int32 nClubId = 1    [default = 0]; //俱乐部id
    required double nChange=2     [default = 0]; //增加退还的俱乐部币数额
    required int32 nType=3        [default = 0]; //1:增加，2:退还
}

//个人俱乐部币增加退还回复 ClubSTransferClubGoldResp_CMD
message ClubSTransferClubGoldResp
{
    required int32 nRlt = 1;    //0:成功 1:参数错误 2:俱乐部不存在 3:不是俱乐部,是大厅 4:俱乐部币不足 5:不是俱乐部成员 6:申请到达上限 7:没有进行安全密码校验 8:安全密码校验失败
    required string sErrStr = 2; //错误信息
    required int32 nType=3; //1:增加，2:退还
}

//个人俱乐部币流水记录请求 ClubSTransferRecordReq_CMD
message ClubSTransferRecordReq
{
    required int32 nClubId=1      [default = 0]; //俱乐部id
    required int32 nIdOfStart=2   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=3 		  [default = 10];//数目
}

//个人俱乐部币流水记录回复 ClubSTransferRecordResp_CMD
//nSourceType 12301:被踢退还 12302:主动退出俱乐部退还 12303:管理员增加 12304:管理员回收 12305:玩家申请增加 12306:玩家申请退还 123:德州输赢 其它:暂定为游戏输赢，后续有再补充
message ClubSTransferRecordResp
{
    message TransferItem
    {
        required int32 nId=1;				//记录id(自增全游戏记录唯一id)
        required double nChange=2;          //变化的俱乐部币数额
        required double nClubGold=3;        //变化后的俱乐部币
        required string sTime 	= 4; 		//记录时间
        required int32 nSourceType=5;		//来源
	}
	repeated TransferItem arrRecords = 1;
    required int32 nClubId=2;               //俱乐部id
	required int32 nAllCnt=3;			    //总数目
}

//俱乐部个人历史牌局请求 ClubSPaiJuRecordReq_CMD
message ClubSPaiJuRecordReq
{
    required int32 nClubId=1      [default = 0]; //俱乐部id
    required int32 nIdOfStart=2   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=3 		  [default = 10];//本页的记录数目
    required int32 nUserId=4      [default = 0]; //查看的玩家 
}

//俱乐部个人历史牌局返回 ClubSPaiJuRecordResp_CMD
message ClubSPaiJuRecordResp
{
	repeated ClubSPaiJuItem arrRecords = 1;
    required int32 nClubId=2;               //俱乐部id
	required int32 nAllCnt=3;			    //总数
    required int32 nUserId=4;               //查看的玩家
}

//牌局信息
message ClubSPaiJuItem
{
    required int32 nId=1;				//记录id(自增全游戏记录唯一id)
    required string sPaiJuID= 2; 		//牌局编号
    required string sTableInfo=3;       //牌桌配置(json)
    required string sHandCards=4;       //手牌信息(json)
    required double nWinLose=5;         //输赢
    required string sTime=6; 		    //记录时间
    required int32 nGameId=7;           //游戏id
    optional int32 nCollect=8;			//是否收藏 0:未收藏 >0:已收藏
}

//俱乐部个人贡献请求(俱乐部收益请求) ClubSContribRecordReq_CMD
message ClubSContribRecordReq
{
    required int32 nClubId=1      [default = 0]; //俱乐部id
    required int32 nUserId=2      [default = 0]; //玩家UserId (传0就是查询俱乐部收益)
    required int32 nIdOfStart=3   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=4 		  [default = 10];//本页的记录数目
    required int32 nType=5 		  [default = 0]; //类型 0:俱乐部币收益 1:金币收益
}

//俱乐部个人贡献返回(俱乐部收益请求) ClubSContribRecordResp_CMD
message ClubSContribRecordResp
{   
    message ContribItem
    {
        required int32 nId=1;				//记录id(自增全游戏记录唯一id)
        required int32 nType=2;             //类型 1:服务费 2:道具 3:保险  101:充值
        required double nContrib=3;         //贡献
        required string sTime=4; 		    //记录时间
        optional int32 nGameId=5;           //游戏Id 
    }
	repeated ContribItem arrRecords = 1;
    required int32 nClubId=2;               //俱乐部id
    required double nTotalContrib=3;        //累计个人贡献(请求时nUserId=0，这个就是俱乐部累计收益)
	required int32 nAllCnt=5;			    //总数
    required int32 nType=6;                 //类型 1:俱乐部币收益 2:金币收益
    required double nServiceCharge=7;       //累计服务费
    required double nPropsIncome=8;         //累计道具
    required double nInsurance=9;           //累计保险
}

//俱乐部黑名单请求 ClubSBlacklistReq_CMD
message ClubSBlacklistReq
{
    required int32 nClubId = 1    [default = 0]; //俱乐部id
    required int32 nIdOfStart=2   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=3 		  [default = 10];//本页的记录数目
}

//俱乐部黑名单回复 ClubSBlacklistResp_CMD
message ClubSBlacklistResp
{
    repeated ClubSBlackList arrBlacklist = 1; //黑名单用户列表
    required int32 nAllCnt = 2; //总数
    required int32 nClubId = 43;//俱乐部id
}

//黑名单管理操作请求 ClubSBlacklistMgrReq_CMD
message ClubSBlacklistMgrReq
{
    required int32 nClubId=1      [default = 0]; //俱乐部id
    required int32 nUserId=2      [default = 0]; //黑名单玩家UserId
    required int32 nOpType=3      [default = 0]; //操作类型:1:加入黑名单 2:从黑名单中移除
}

//黑名单管理操作返回 ClubSBlacklistMgrResp_CMD
message ClubSBlacklistMgrResp
{
    required int32 nRlt = 1;     //0:成功 1:不是俱乐部,是大厅 2:参数错误 3:俱乐部不存在 4:权限不足 5:已在黑名单中 6：你不是俱乐部成员
    required string sErrStr = 2; //错误信息
    required int32 nUserId=3;    //黑名单玩家UserId
    required int32 nOpType=4;    //操作类型 1:加入黑名单 2:从黑名单中移除
    required int32 nClubId=5;    //俱乐部id
}

//黑名单玩家搜索请求 ClubSBlacklistSearchReq_CMD
message ClubSBlacklistSearchReq
{
    required int32 nClubId = 1  [default = 0];  //俱乐部id
    required string str = 2     [default = ""]; //检索字符串
}

//黑名单玩家搜索返回 ClubSBlacklistSearchResp_CMD
message ClubSBlacklistSearchResp
{
    repeated ClubSBlackList arrBlacklist = 1; //黑名单用户列表
    required int32 nPage = 2; //第几页
    required int32 nAllPage = 3; //总页数
    required int32 nClubId = 4; //俱乐部id
}

//俱乐部黑名单用户信息
message ClubSBlackList
{   
    required int32 nId=1;		    //记录id(自增全游戏记录唯一id)
    required int32 nUserId=2;		//玩家id
	required string sFaceId=3;		//url
	required string sName=4;		//昵称
	required int32 nSex=5;	    	//性别 0:男 1:女
    required string sTime=6;	    //加入黑名单的时间
    required string sShopAcc=7;     //第三方id
}

//俱乐部牌桌记录请求 ClubSTableRecordReq_CMD
message ClubSTableRecordReq
{
    required int32 nClubId = 1    [default = 0]; //俱乐部id
    required int32 nIdOfStart=2   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=3 		  [default = 10];//本页的记录数目
}

//俱乐部牌桌记录返回 ClubSTableRecordResp_CMD
message ClubSTableRecordResp
{
    message TableRecordItem
    {
        required int32  nId=1;				    //记录id(自增全游戏记录唯一id)
        required string sTableId=3;				//牌桌id
        required string sTableInfo=4;			//牌桌配置
        required string sTime=6;	    		//创建时间
    }
    repeated TableRecordItem arrRecords = 1;
    required int32 nAllCnt = 2; //总数
    required int32 nClubId = 3;
}

//俱乐部牌桌参与玩家请求 ClubSTableUserReq_CMD
message ClubSTableUserReq
{
    required string sTableId=1    [default = ""]; //牌桌id
    required int32 nIdOfStart=2   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=3 		  [default = 10];//本页的记录数目
}

//俱乐部牌桌参与玩家返回 ClubSTableUserResp_CMD
message ClubSTableUserResp
{   
    repeated ClubSTableUser arrUser = 1; //俱乐部成员数组
    required int32 nAllCnt = 2; //总数
}

//俱乐部牌桌玩家
message ClubSTableUser
{   
    required int32 nId = 1;                 //记录id(自增全游戏记录唯一id)
    required int32 nUserId=2;				//玩家id
    required string sFaceId=3;				//url
    required string sName=4;				//昵称
    required int32 nSex=5;	    			//性别 0:男 1:女
    required int32 nClubId=6;               //俱乐部id
    required int32 nIdentify=7;             //身份  1:主席  10:管理员  20:普通成员
    required string sShopAcc=8;             //第三方id
    required int32 nPlayCnt=9;              //局数
    required double nWinLose=10;             //输赢
    required double nContribution=11;       //贡献
    required double nItemId=12;             //道具id 1金币 其它:俱乐部币
}

//俱乐部成员信息请求 ClubSMemberInfoReq_CMD
message ClubSMemberInfoReq
{
    required int32 nUserId =1   [default = 0];
    required int32 nClubId = 2  [default = 0];
}

//俱乐部成员信息返回 ClubSMemberInfoResp_CMD
message ClubSMemberInfoResp
{   
    required int32 nRlt = 1;     //0:成功 1:是大厅不是俱乐部 2:玩家不存在
    required string sErrStr = 2; //错误信息
    required int32 nUserId = 3;
    required int32 nClubId = 4;
    optional ClubSUser tUserInfo = 5; //俱乐部玩家信息,成功才有
}

//俱乐部管理员列表请求 ClubSAdminListReq_CMD
message ClubSAdminListReq
{
    required int32 nClubId = 1  [default = 0];
    required int32 nCnt=2 		[default = 10];//本页的记录数目
	required int32 nPage=3 		[default = 1]; //第几页 nPage>=1
}

//俱乐部管理员列表返回 ClubSAdminListResp_CMD
message ClubSAdminListResp
{
    repeated ClubSUser arrAdminList = 1;  //管理员列表
    required int32 nClubId = 2;
    required int32 nPage = 3;
    required int32 nAllCnt = 4; //总数目
}

//俱乐部增加删除管理员请求 ClubSAdminMgrReq_CMD
message ClubSAdminMgrReq
{
    required int32 nClubId=1      [default = 0]; //俱乐部id
    required int32 nUserId=2      [default = 0]; //被操作的玩家UserId
    required int32 nOpType=3      [default = 0]; //操作类型:1:增加管理员 2:删除管理员
}

//俱乐部增加删除管理员返回 ClubSAdminMgrResp_CMD
message ClubSAdminMgrResp
{
    required int32 nRlt = 1;     //0:成功 1:是大厅不是俱乐部 2:参数错误 3:俱乐部不存在 4:你不是主席 5:玩家不存在 6:已是管理员 7:修改的玩家是主席 8:管理员数目达到上限 9:玩家不是管理员
    required string sErrStr = 2; //错误信息
    required int32 nUserId=3;    //被操作的玩家UserId
    required int32 nOpType=4;    //操作类型 1:增加管理员 2:删除管理员
    required int32 nClubId = 5;
    optional ClubSUser tAdmin=6;//管理员信息(nRlt=0,nOpType=1才有)
}

//修改管理员权限请求 ClubSChangeAdminPowerReq_CMD
message ClubSChangeAdminPowerReq
{   
    message ClubSPower
    {   
        required int32 nPowerType=1; //权限类型:1:成员管理权限 2:俱乐部币管理权限 3:开桌管理权限
        required bool isOpen=2;      //是否开启 true:开启  false:关闭
    }
    required int32 nClubId=1                [default = 0]; //俱乐部id
    required int32 nUserId=2                [default = 0]; //被操作的玩家UserId
    repeated ClubSPower arrPower = 3;                      //修改的权限数组
}

//修改管理员权限返回 ClubSChangeAdminPowerResp_CMD
message ClubSChangeAdminPowerResp
{
    required int32 nRlt = 1;           //0:成功 1:是大厅不是俱乐部 2:参数错误 3:俱乐部不存在 4:不是主席 5:玩家不存在 7:修改的玩家是主席
    required string sErrStr = 2;       //错误信息
    required int32 nUserId=3;          //被操作的玩家UserId
    required int32 nClubId = 4;
    optional string sPower = 5;        //最新的玩家权限(成功才有)
}

//俱乐部账户的俱乐部币流水请求 ClubSGoldChangeRecordReq_CMD
message ClubSGoldChangeRecordReq
{
    required int32 nClubId = 1    [default = 0]; //俱乐部id
    required int32 nIdOfStart=2   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=3 		  [default = 10];//本页的记录数目
}

//俱乐部账户的俱乐部币流水返回 ClubSGoldChangeRecordResp_CMD
message ClubSGoldChangeRecordResp
{
    message ChangeRecordItem
    {
        required int32  nId=1;				    //记录id(自增全游戏记录唯一id)
        required int32 nUserId=2;               //玩家id (nUserId=0就是系统)
        optional string sName=3;				//玩家昵称(nUserId>0才有)
        required double nChange=4;			    //改变值
        required string sTime=5;	    		//时间
    }
    repeated ChangeRecordItem arrRecords = 1;
    required int32 nAllCnt = 2; //总数
    required int32 nClubId = 3;
}

//俱乐部申请列表请求 ClubSApplyListReq_CMD
message ClubSApplyListReq
{
    required int32 nClubId = 1    [default = 0]; //俱乐部id
    required int32 nType = 2      [default = 0]; //申请类型: 1:增加俱乐部币 2:退还俱乐部币 3:加入俱乐部
    required int32 nIdOfStart=3   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=4 		  [default = 10];//本页的记录数目
}

//俱乐部申请列表返回  ClubSApplyListResp_CMD
message ClubSApplyListResp
{
    message ApplyList
    {
        required int32  nId=1;				    //记录id(自增全游戏记录唯一id)
        required int32 nUserId=2;				//申请者的UserId
        required string sFaceId=3;				//url
	    required string sName=4;				//昵称
	    required int32 nSex=5;	    			//性别 0:男 1:女
        required string sTime=6;	    		//时间
        required int32 nType=7;                 //申请类型: 1:增加俱乐部币 2:退还俱乐部币 3:加入俱乐部
        optional double nChange=8;              //俱乐部币变化值(nType=1和nType=2才有)  
    }
    repeated ApplyList arrApplyList = 1;
    required int32 nAllCnt = 2; //总数
    required int32 nClubId = 3;
    required int32 nType = 4;
}

//俱乐部申请处理请求 ClubSApplyHandleReq_CMD
message ClubSApplyHandleReq
{
    required int32 nClubId=1      [default = 0]; //俱乐部id
    required int32 nId=2          [default = 0]; //记录id(自增全游戏记录唯一id)
    required int32 nType=3        [default = 0]; //处理的申请类型: 1:增加俱乐部币 2:退还俱乐部币 3:加入俱乐部
    required int32 nOpType=4      [default = 0]; //操作类型: 1:同意 2:拒绝 
    optional string sPassWord=5   [default = ""];//库存密码(nType=1和nType=2要传)(Base64编码)
}

//俱乐部申请处理返回 ClubSApplyHandleResp_CMD
message ClubSApplyHandleResp
{
    required int32 nRlt = 1;     //0:成功 1:大厅,不是俱乐部 2:权限不足 3:俱乐部不存在 4:参数错误 
                                 //5:已被处理 6:俱乐部的俱乐部币不足 7:玩家的俱乐部币不足 8:操作者不是俱乐部成员
                                 //9:申请不存在 10:被操作者不是俱乐部成员 11:密码错误 12:正在被其它管理员处理
                                 //13:修改俱乐部币失败 14:被操作的玩家在游戏中,稍后为你处理 15:数据库操作失败 16:俱乐部已满人
    required string sErrStr = 2; //错误信息
    required int32 nId=3;        //记录id(自增全游戏记录唯一id)
    required int32 nType=4;      //处理的申请类型: 1:增加俱乐部币 2:退还俱乐部币 3:加入俱乐部
    required int32 nClubId=5;
    required int32 nOpType=6;
}

//邀请用户请求 ClubSInviteUserReq_CMD
message ClubSInviteUserReq
{
    required int32 nClubId=1      [default = 0]; //俱乐部id
    required int32 nUserId =2     [default = 0]; //受邀请的玩家
}

//邀请用户返回 ClubSInviteUserResp_CMD
message ClubSInviteUserResp
{
    required int32 nRlt = 1;     //0:成功 1:不是私人俱乐部 2:权限不足 3:邀请玩家不存在 4:已邀请 5:已经是俱乐部成员 6:俱乐部不存在 7:你不是俱乐部成员
    required string sErrStr = 2; //错误信息
    required int32 nClubId=3;
    required int32 nUserId=4;
}

//搜索用户请求 ClubSSearchUserReq_CMD
message ClubSSearchUserReq
{   
    required string str = 1     [default = ""]; //检索字符串
    required int32 nClubId=2    [default = 0]; //俱乐部id
}

//搜索用户返回 ClubSSearchUserResp_CMD
message ClubSSearchUserResp
{  
    message SearchPerson
	{
		required int32 nUserId=1;				//玩家id
		required string sFaceId=2;				//url
		required string sName=3;				//昵称
		required int32 nSex=4;	    			//性别 0:男 1:女
		required int32 nStatus=5;				//0:可邀请 1:已邀请 2:已在俱乐部
		required string sTime=6;                //账号创建时间
	} 
    repeated SearchPerson arrUser = 1; //用户数组
    required int32 nPage =2;
    required int32 nAllPage=3; 
}

//玩家个人信息请求 ClubSUserInfoReq_CMD
message ClubSUserInfoReq
{
    required int32 nUserId =1   [default = 0];
}

//玩家个人信息返回 ClubSUserInfoResp_CMD
message ClubSUserInfoResp
{   
    required int32 nRlt = 1;     //0:成功 1:参数错误 2:玩家不存在
    required string sErrStr = 2; //错误信息
    optional ClubSUserInfo tUserInfo = 3; //个人信息,成功才有
}

//个人信息(生涯,我的)
message ClubSUserInfo 
{
    required int32 nUserId=1;				//玩家id
	required string sFaceId=2;				//url
	required string sName=3;				//昵称
	required int32 nSex=4;	    			//性别 0:男 1:女
    required double nGold=5;				//金币
    required string sTime=6;                //账号创建时间
    required string sPhone=7;               //手机号
    required int32  nAllCount=8;            //总场次
    required double nMaxProfit=9;           //单场最高盈利
    optional string sPersonality=10;        //个性签名
    optional int32  nHandCount=11;          //总手数
    optional double nMaxHandProfit=12;      //单手最高盈利
    optional int32 nVip=13;                 //vip等级
    optional int32 nExp=14;                 //经验
    optional int32 nGloryLevel=15;          //荣誉等级
    optional int32 nLevelStart=16;          //等级的星星
    optional int32 nOpenProtection=17;		//是否开启安全保护 0:不开启 1:开启
    optional double nWithDrawGold =18;      //可提现金币
    optional double nNotWithDrawGold=19;    //不可提现金币
    optional int32 nCash = 20;              //现金
    optional int32 nReviewedGold = 21;      //待审核金币
    optional double nExchangeRate= 22; 	    //汇率:   货币转金币的汇率 
    optional int32 nTransSwitch = 23;       //转账权限开关 0:开 1:关
	optional string sMail =24;				//邮箱
    optional int32 nFreeCount = 25;         //改名次数
    optional double nPrice = 26;            //改名金额
}

//修改玩家个人信息请求 ClubSChangeUserInfoReq_CMD
message ClubSChangeUserInfoReq
{   
    message ChangeItem
    {
        required string sKey = 1;  //修改的项 sFaceId:头像,sName:昵称,nSex:性别,sPhone:手机号,sPersonality:个性签名,sSafePassWard:安全密码
        required string sVal = 2;  //修改值
    }
    repeated ChangeItem arrChange =1;
    optional string code =2;        //验证码
    optional string oldPass =3;        //旧密码
    optional int32 nPurpose=4;              //验证码用途(0:注册与绑定; 1:密码重置 2:修改支付密码)
}

//修改玩家个人信息返回 ClubSChangeUserInfoResp_CMD
message ClubSChangeUserInfoResp
{   
    message RltItem
    {
        required int32 nRlt = 1;    //0:成功 1:参数错误,2:被占用 3:不符合要求 4:新旧值相同 5:名字超长 6:含有特殊字符 7:含有敏感词 8:个性签名超长 9:金币不足 10:安全密码不符合要求
                                    // 11:没有进行安全密码校验 12:安全密码校验失败
        required string sKey = 2;  //修改的项 sFaceId,sName,nSex,sPhone,sPersonality,sSafePassWard
    }
    repeated RltItem arrRlt = 1; //修改结果
    required int32 nRlt = 2;//总的修改结果,所有项都修改成功才算成功，其中一项失败都算失败 0:成功 1:失败  
}

//牌谱请求 ClubSPaiPuReq_CMD
message ClubSPaiPuReq
{
    required int32 nType=1        [default = 0];  //类型:1:近期  2:收藏
    required int32 nIdOfStart=2   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=3 		  [default = 10];//本页的记录数目
    required int32 nGameId = 4    [default = 0];//游戏id
}

//牌谱返回 ClubSPaiPuResp_CMD
message ClubSPaiPuResp
{   
    repeated ClubSPaiJuItem arrRecords = 1;
    required int32 nType=2;                     //类型:1:近期  2:收藏
    required int32 nAllCnt = 3; //总数
    required int32 nGameId = 4; //游戏id
}

//操作牌谱请求 ClubSOpratePaiPuReq_CMD
message ClubSOpratePaiPuReq
{
    required int32 nType=1      [default = 0];  //类型:1:收藏  2:取消收藏
    required string sPaiJuID=2  [default = ""]; //牌局编号
}

//操作牌谱返回 ClubSOpratePaiPuResp_CMD
message ClubSOpratePaiPuResp
{
    required int32 nRlt = 1;     //0:成功 1:牌局不存在 2:参数错误 3:不是你的牌局 4:已收藏 99：DB操作异常
    required string sErrStr = 2; //错误信息
    required int32 nType=3;      //类型:1:收藏  2:取消收藏
    required string sPaiJuID= 4; //牌局编号
}

//回放数据请求 ClubSPlaybackDataReq_CMD
message ClubSPlaybackDataReq
{
    required string sPaiJuID= 1 [default = ""]; //牌局编号
}

//回放数据返回 ClubSPlaybackDataResp_CMD
message ClubSPlaybackDataResp
{
    required int32 nRlt = 1;     //0:成功 1:牌局不存在
    required string sErrStr = 2; //错误信息
    required string sPaiJuID = 3;  //牌局id
    optional int32 nGameId = 4;  //游戏id(nRlt=0才有)
    optional string sJson = 5;   //牌局回放数据(nRlt=0才有)
    optional string sTime = 6;   //时间(nRlt=0才有)
	optional string sTableName=7;//桌子名称
}

//个人通知请求 ClubSUserNoticeReq_CMD
message ClubSUserNoticeReq
{
    required int32 nIdOfStart=1   [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=2 		  [default = 10];//本页的记录数目
    required int32 nType=3        [default = 0];//通知的类型 1:系统通知 2:俱乐部邀请通知 3:个人加入俱乐部申请
}

//个人通知返回 ClubSUserNoticeResp_CMD
message ClubSUserNoticeResp
{
    repeated ClubSNoticesItem arrNotices = 1; ///nType=1或者nType=2才有
    required int32 nAllCnt = 2; //总数
    required int32 nType=3; //通知的类型 1:系统通知 2:俱乐部邀请通知 3:个人加入俱乐部申请
    repeated ClubSPersonApply arrApplyList = 4; //nType=3才有
    optional int32 nUnReadCnt = 5;  //未读的系统消息数量 nType=1才有
}

message ClubSNoticesItem
{
    required int32 nId=1;				//记录id(自增全游戏记录唯一id)
    required int32 nType=2;             //消息分类 1:系统通知 2:俱乐部邀请通知 4:Mtt比赛领奖通知 5:Mtt比赛取消通知
    required int32 nStatus=3;           //状态 0:未处理,1:同意 2:拒绝 3:不需要处理 4:已失效  5:已领取
    required string sTime=4; 		    //时间
    required string sData=5;            //数据,json格式,nType=2时,结构={sClubName=俱乐部名字,nClubId=俱乐部id,nUserId=邀请者id,sUserName=邀请者名字,sFaceId=邀请者头像} 
                                        //  nType=1时,结构={sClubName=俱乐部名字,nClubId=俱乐部id,nUserId=管理员id,sUserName=管理员名字,sFaceId=管理员头像
                                        //        nOpType=操作类型:1:增加俱乐部币 2:回收俱乐部币 3:提升为管理员 4:降成普通成员 5:踢出 6:修改权限 7:处理申请加入 8:处理俱乐部币申请 9:处理俱乐部币退还申请
                                        //        nChange=变化的俱乐部币,arrChangePower={{nPowerType,isOpen},...},isAgree=1:同意 2:拒绝}
										
										//nType=4时,{sName=比赛名称Base64,nGold=获奖金币,nEventId=比赛ID,nRank=比赛名次,nGameId=游戏id}
										//nType=5时,{sName=比赛名称Base64,nEventId=比赛ID}
										
										
    optional int32 nHadRead=6;          //是否已读 0:未读 1:已读  nType=1才有
}

//处理个人通知请求 ClubSUserNoticeHandleReq_CMD
message ClubSUserNoticeHandleReq
{
    required int32 nId=1       [default = 0];//记录id(自增全游戏记录唯一id)
    required int32 nOpType=2   [default = 0];//操作类型:1同意，2拒绝 3Mtt比赛领奖
}

//处理个人通知返回 ClubSUserNoticeHandleResp_CMD
message ClubSUserNoticeHandleResp
{
    required int32 nRlt = 1;     //0:成功 1:参数错误 2:无需处理 3:已处理 4:俱乐部不存在 5:俱乐部已满人 6:已失效 7:不是你的通知 8:没有这条通知 9:玩家通知的额外信息错误 10：已经是俱乐部成员 99:数据库操作异常
    required string sErrStr = 2; //错误信息
    required int32 nId=3;        //记录id(自增全游戏记录唯一id)
    required int32 nOpType=4;    //操作类型:1同意，2拒绝 3Mtt比赛领奖
}

//获取玩家的俱乐部列表请求 ClubSGetUserClubListReq_CMD
message ClubSGetUserClubListReq
{
    required int32 nUserId=1 [default = 0]; //玩家id
}

//获取玩家的俱乐部列表返回 ClubSGetUserClubListResp_CMD
message ClubSGetUserClubListResp
{
    repeated ClubSItem arrClub = 1; //俱乐部列表
    required int32 nPage=2;//当前页
    required int32 nAllPage=3;//总页数
}

message ClubSItem 
{
    required int32 nClubId = 1;//俱乐部id
    required string sClubName=2;//俱乐部名称(Base64编码)
    required int32 nMaster=3;//主席id
}

//俱乐部场景信息改变通知 ClubSSceneChangeNotify_CMD
// optional string sClubName                俱乐部名称
// optional double nClubGold                俱乐部资产(俱乐部币)
// optional double nIncome                  总收益(俱乐部币)
// optional double nTodayIncome             今日收益(俱乐部币)
// optional int32 nMaxUserCnt               俱乐部人数上限
// optional int32 nClubTax                  俱乐部桌服务费分成(在抽水中的占比),需要除以1000,如分成=95%,nClubTax=950
// optional int32 nInsuranceTax             俱乐部桌保险分成(在保险中的占比),需要除以1000,如分成=95%,nInsuranceTax=950
// optional int32 nCanSearch                是否允许搜索 0:允许 1:不允许
// optional int32 nCanApply                 是否允许申请加入 0:允许 1:不允许
// optional string sPassWord                库存密码
// optional int32 nUserCnt                  成员人数
// optional int32 nApplyJionCnt             加入俱乐部申请数目(有成员管理权限的用户才有)
// optional int32 nApplyAddGoldCnt          增加俱乐部币申请数目(有俱乐部币管理权限的用户才有)
// optional int32 nApplyCutGoldCnt          增加俱乐部币申请数目(有俱乐部币管理权限的用户才有)
// optional ClubSUser tMasterInfo           主席信息
// optional bool IsUseGold                  俱乐部是否使用金币
// optional bool IsUserClubGold             俱乐部是否使用俱乐部币
// optional double nGold                    俱乐部资产(金币)
// optional double nGoldIncome              总收益(金币)
// optional double nGoldTodayIncome         今日收益(金币)
message ClubSSceneChangeNotify
{
    required int32 nClubId = 1;           //俱乐部id
    required string sChangeInfo = 2;       //改变的信息
}

//俱乐部玩家信息改变通知 ClubSUserInfoChangeNotify_CMD
// optional double nGold            金币
// optional double nClubGold        俱乐部币
// optional string sPower           权限 json格式 [{nPowerType,isOpen},...]
// optional int32 nIdentify         身份  1:主席  10:管理员  20:普通成员
// optional int32 nWeekCount        本周局数
// optional double nContribution    累计贡献(俱乐部币)
// optional double nGoldContribution 累计贡献(金币)
message ClubSUserInfoChangeNotify
{   
    required int32 nClubId = 1;                         //俱乐部id
    required int32 nUserId = 2;                         //玩家id
    required string sChangeInfo = 3;                     //改变的信息
}

//踢出俱乐部通知 ClubSKickOutNotify_CMD
message ClubSKickOutNotify
{
    required int32 nClubId = 1;           //俱乐部id
    required int32 nUserId = 2;           //玩家id
    required string sClubName = 3;        //俱乐部名字
}

//玩家消息通知(非俱乐部) ClubSUserMsgNotify_CMD
message ClubSUserMsgNotify
{   
    message MsgUser
    {
        required int32 nUserId = 1;  //玩家id
        required string sUserName = 2; //玩家名字
        required string sFaceId = 3; //头像
    }   
    required int32 nUserId = 1;                         //玩家id
    required int32 nType = 2;                           //类型 1:俱乐部申请结果 2:收到俱乐部邀请 3:同意邀请进入俱乐部 4:俱乐部币申请结果 5:俱乐部币退还申请结果 6:管理员操作 7:后台审核消息
    optional ClubSPersonApply tApply = 3;               //申请的处理结果, nType=1,4,5才有,用来刷新个人未处理申请
    optional ClubSNoticesItem tNoticesItem = 4;         //玩家个人通知,nType=1,4,5,6时是系统消息 nType=2时是俱乐部邀请通知
    optional ClubSItem tClubInfo = 5;                   //俱乐部信息,nType=1,3,4,5,6才有
    optional MsgUser tUserInfo = 6;                     //俱乐部信息,nType=1,4,5,6才有,管理员的信息
    repeated ClubSRedotData arrRedot = 7;               //红点信息,nType=1,2,4,5,6,7才有
}

//获取后台配置请求 ClubSGetGameParamsReq_CMD
message ClubSGetGameParamsReq
{
    required int32 nGameId = 1          [default=0]; //游戏id
}

//获取后台配置返回 ClubSGetGameParamsResp_CMD
/*德州 {
    arrCapacityOption=可选人数,自动开始人数 如[2,3,4,5,6],
    arrConfigOption=[[小盲,大盲,默认带入,前注,付费看手牌,付费看公牌,付费切牌],...] 如[[1,2,200,[0,1,2],1,1,1],[2,4,400,[0,1,2,4],2,2,2],...],
    arrKeepTimeOption=可选房间时长(小时) 如[1,1.5,2,2.5,3],
    arrTakeinOption=带入筹码倍数 如[0.5,1,1.5,2],
    arrPoolEntryRateOption=入池率 如[25,30,35,40,45],
    arrDWLimitOption=抽水封顶 如[1,2,3,4]个大盲
    int nVideoFee 		--实时语音收费金额
    }
*/
message ClubSGetGameParamsResp
{
    required string sGameConfig = 1; //后台配置 
    required int32 nGameId = 2;//游戏id
}

//俱乐部开桌请求 ClubSOpenTableReq_CMD
/*
    --俱乐部房配置
    int  nKeepTime       --房间时长(秒)
    int  nGoldType	        --使用的金币类型 1:金币 2:俱乐部币 3:积分
    string sTableName       --牌桌名称

    --俱乐部德州公共配置(德州，短牌，奥马哈)
    double nSmallBlind		    --小盲
    double nBigBlind		    --大盲
    double nTakeIn		        --默认带入
    int nCapacity	 	        --人数配置 (2~9)
    double nPreAnte  			--前注
    tAutostart = {			    --自动开始设置
        bool isOpen			    --是否开启功能 true：开启 false:关闭
        int nPlayerCnt		    --自动开始的人数 >=2人
    }
    double nMinTabkeInBB	    --带入筹码倍数最小值
    double nMaxTabkeInBB	    --带入筹码倍数最大值
    double nPoolEntryRate 	--入池率 0%~100%，95%就是95
    bool  isOnlyPlayByIOS	--true:只能IOS设备玩 fasle:所有设备都能玩
    bool isForceBlind 	 	--强制盲注 true:开启 false:关闭
    bool isGPSLimit			--GPS限制 禁止地理位置接近的玩家同时在一张桌子上进行牌局  true:开启 false:关闭
    bool isIPLimit			--IP限制 禁止相同IP地址的玩家同时在一张桌子上进行牌局  true:开启 false:关闭
    bool isAOF				--全下或弃牌 true:开启 false:关闭
    bool isDelayLook		--延迟看牌 true:开启 false:关闭
    int nInsureMode			--保险模式 0:无保险 1:传统保险 2:低水保险
    bool isTabkeOut         --是否开启带出筹码功能 true:开启 false:关闭

    tDrawWaterMode = {		--抽水模式
        int nModeType		--抽水类型 1:按比例就是把抽   3:局抽  0:不收取
        int nComputeMode	--抽取方式 1:按净盈利  2:按底池

		--按牌桌比例收取
        double nTaxRate			--比例 百分制  如2%就是2
		
        -- 按奖池比例收取
        double nTaxRate			--比例 百分制  如2%就是2
        double nTopLimitBB		--封顶 多少个大盲
        bool isFreeBeforeFlop 	--翻牌前结束免服务费 true:是 false：否
        bool isHalf				--低于3人服务费5折 true:是 false：否
        tFreeConfig = {			--盈利过低免服务费
            bool isOpen			--是否开启功能 true：开启 false:关闭
            double nLimitBB		--多少倍大盲
        }

        --固定收取
        double nCutoffValue		--分界值
        double nLessValue		--当净盈利小于分界值固定收多少
        double nGreaterValue	--当净盈利大于等于分界值固定收多少
        
    }	

    --短牌专属字段
	bool isDPreAnte			--庄家是否要下两倍前注 true:开启 false:关闭

    int nIsPerson        --是否私人房间 0否 1是
    int nIsShow          --是否显示房间 0否 1是
    string sPassWord     --私人房间密码 默认 ""
    int nPoolEntryRateHands --入池率多少手不限制
    int nPoolHands          --手数限制
    nTableCost = [{nId = 1, nCost = 10},{nId = 2, nCost = 10},{nId = 3, nCost = 10}]  付费看公牌1 付费看手牌2 付费切牌3
    int preAnteOdd         --庄家n倍数前注
    double nLoseMaxAmount  --输钱限制
    int nTabkeOutOdd       --撤码阈值的倍数N
    int nMutedUnSite     --观众禁言 0否 1是
    bool isVideoFee		--实时语音收费 true:开启 false:关闭
    int nVideoFee 		--实时语音收费金额
*/
message ClubSOpenTableReq
{
    required int32 nClubId = 1          [default=0]; //俱乐部id
    required int32 nGameId = 2          [default=0]; //游戏id
    required string sConfig = 3         [default=""]; //桌子配置 
}

//俱乐部开桌返回 ClubSOpenTableResp_CMD
/*0:成功 1:参数错误 2:俱乐部不存在 3:权限不足 4:游戏服没有启动 5:开桌失败 6:操作者不是俱乐部成员 7:有相同名字的牌桌了 
8：开桌数目达到上限 9:开桌超时 10:上一次的开桌还没处理完，请稍后 11.桌子名字过长 12:后台没开金币桌开关 13:后台没开俱乐部币桌开关
14:货币类型不正确 15:小盲类型不正确 16:小盲数值不正确 17:大盲类型不正确 18:大盲数值不正确 19:大盲<2倍小盲 20:前注类型错误
21:前注数值不正确 22:默认带入类型错误 23:默认带入数值不正确 24:人数类型错误 25:人数不在2~9范围内 26:自动开始人数类型错误
27:自动开始不在2~开桌人数范围内 28:带入筹码倍数最小值类型错误 29:带入筹码倍数最小值数值不正确 30:带入筹码倍数最大值类型错误
31:带入筹码倍数最大值数值不正确 32:带入筹码倍数最小值>带入筹码倍数最大值 33:入池率类型错误 34:入池率不在0~100%范围内
35:只能IOS设备玩类型错误 36:强制盲注类型错误 37:GPS限制类型错误 38:IP限制类型错误 39:全下或弃牌类型错误 40:延迟看牌类型错误
41:保险模式类型错误 42:保险模式不是0:无保险,1:传统保险,2:低水保险的任意一个 43:抽水模式类型错误 44:抽水类型不是0:不收取,1:按奖池比例收取,2:固定收取的任意一个
45:抽取方式不是1:按净盈利,2:按底池的任意一个 46:抽水比例类型错误 47:抽水比例不在0~100%范围内 48:封顶类型错误 49:封顶<0
50:翻牌前结束免服务费类型错误 51:低于3人服务费5折类型错误 52:盈利过低免服务费类型错误 53:盈利过低免服务费数值<0 54:分界值类型错误
55:分界值<0 56:当净盈利小于分界值固定收取抽水类型错误 57:当净盈利小于分界值固定收取抽水<0 58:当净盈利大于等于分界值固定收取抽水类型错误
59:当净盈利大于等于分界值固定收取抽水<0 60:金币不足 61:抽取方式类型错误 62:带出筹码类型错误 63:庄家下两倍前注类型错误
*/
message ClubSOpenTableResp
{
    required int32 nRlt = 1; 
}

//俱乐部开桌通知 ClubSOpenTableNotify_CMD
/*
    俱乐部房配置
    string sTableId             --牌桌id
    int nGameId                 --游戏id
    int nClubId                 --俱乐部id
    string sTableName           --牌桌名称
    int nCapacity               --最大人数
    int nNowCnt                 --目前人数
    int nKeepTime               --房间时长(秒) -1:永久桌，不显示具体时间
    int nOpentime               --开桌时间  
    int nGoldType               --使用的金币类型(1金币 2俱乐部币 3积分)
    int nLiveUserID             --房主id
    int nUseTime                --已使用的时间(秒) nKeepTime=-1没有这个字段
    int nTableIndex             --牌桌的下标

    俱乐部德州配置
    double nSmallBlind             --小盲
    double nBigBlind               --大盲
    int nTableStatus            --房间状态 0:正常状态 1:暂停状态,停止计时
*/
message ClubSOpenTableNotify
{
    required int32 nClubId = 1; //俱乐部id
    required string sTableId = 2; //牌桌id
    required string sTableInfo =3; //牌桌信息
}

//俱乐部关桌请求 ClubSCloseTableReq_CMD
message ClubSCloseTableReq
{
    required int32 nClubId = 1  [default=0]; //俱乐部id
    required string sTableId = 2 [default=""]; //牌桌id
}

//俱乐部关桌返回 ClubSCloseTableResp_CMD
message ClubSCloseTableResp
{
    required int32 nRlt = 1; //0:成功 1:参数错误 2:俱乐部不存在 3:权限不足 4:牌桌不存在 5:游戏服没有启动 6:不是你开的桌子,不能关闭 7:关桌超时 8:上一次的关桌还没处理完，请稍后 9:关桌失败, 游戏已开始
}

//俱乐部关桌通知 ClubSCloseTableNotify_CMD
message ClubSCloseTableNotify
{
    required int32 nClubId = 1; //俱乐部id
    required string sTableId = 2; //牌桌id
}

//俱乐部牌桌列表请求 ClubSGetTableListReq_CMD
message ClubSGetTableListReq
{
    required int32 nClubId = 1      [default=0]; //俱乐部id
    optional int32 nGameId = 2      [default=0]; //游戏id：0全部游戏
    required int32 nCnt = 3         [default=10]; //多少条
    required int32 nTableIndex=4    [default=0];//最后一张牌桌的index，第一次发0    
    optional string sScreen = 5;    //筛选：有则筛选   json 
    /*
        arrChipLevel={{0-10},{10-50}} --筹码级别（指大盲配置）：0-10，10-50，50-100，100-1000，1000-100000000
        arrPlayerCnt={{2-2},{3-6}}    --指定人数（指牌桌座位）：2-2人，3-6人,7-9人
        isForceBlind                  --是否强制盲注 
        isAOF			              --是否仅限AllIn和弃牌 
        isOpenInsure	              --是否开保险 
        isVacancy	                  --是否 空位 
    */
}

//俱乐部牌桌列表返回 ClubSGetTableListResp_CMD
//arrTableInfo = [sTableInfo,sTableInfo,...]
//sTableInfo 具体的字段定义看 ClubSOpenTableNotify 的注释
message ClubSGetTableListResp
{
    required int32 nClubId = 1; //俱乐部id
    repeated string arrTableInfo = 2;//牌桌信息
}

//俱乐部牌桌信息变化通知 ClubSTableInfoNotify_CMD
//sTableInfo 具体的字段定义看ClubSOpenTableNotify的注释
message ClubSTableInfoNotify
{
    required int32 nClubId = 1; //俱乐部id
    required string sTableId = 2; //牌桌id
    required string sTableInfo =3; //发生改变的牌桌信息
}

//俱乐部关闭通知  ClubSCloseNotify_CMD
message ClubSCloseNotify
{
    required int32 nClubId = 1; //俱乐部id
}

//服务器维护通知(需要重新登录俱乐部) ClubSMaintenanceNotify_CMD
message ClubSMaintenanceNotify
{
    required string sTime = 1; //时间
}

//玩家俱乐部币申请记录请求（玩家个人） ClubSGetApplyListReq_CMD
message ClubSGetApplyListReq
{
    required int32 nType = 1                [default = 0]; //状态类型: 0:所有 1:可撤回 2:不可撤回
    required int32 nIdOfStart = 2           [default = 0]; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt = 3 		        [default = 10];//本页的记录数目
    required int32 nClubId = 4              [default = 0];//俱乐部id
}

//玩家俱乐部币申请记录返回（玩家个人） ClubSGetApplyListResp_CMD
message ClubSGetApplyListResp
{   
    repeated ClubSPersonApply arrApplyList = 1;
    required int32 nType = 2; //状态类型: 0:所有 1:可撤回 2:不可撤回
    required int32 nAllCnt = 3; //总数目
    required int32 nClubId = 4; //俱乐部id
}

//申请信息
message ClubSPersonApply
{
    required int32  nId=1;				    //记录id(自增全游戏记录唯一id)
    required int32 nClubId=2;				//俱乐部id
    required string sClubName=3;			//俱乐部名字
    required string sTime=4;	    		//时间
    required int32 nType=5;                 //申请类型: 1:增加俱乐部币 2:退还俱乐部币 3:加入俱乐部
    required int32 nStatus=6;               //申请状态 0:未处理,1:同意 2:拒绝 3:已失效 4:已撤回
    optional double nChange=7;              //俱乐部币变化值(nType=1和nType=2才有)
}

//玩家申请处理请求（玩家个人） ClubSUserApplyOpReq_CMD
message ClubSUserApplyOpReq
{
    required int32  nId=1                   [default = 0];//记录id(自增全游戏记录唯一id)
    required int32  nOpType=2               [default = 0];//操作类型: 1:撤回申请
    required int32  nType=3                 [default = 0];//申请类型: 1:增加俱乐部币 2:退还俱乐部币 3:加入俱乐部
}

//玩家申请处理返回（玩家个人） ClubSUserApplyOpResp_CMD
message ClubSUserApplyOpResp
{
    required int32  nRlt = 1; //结果 0：成功 1:申请不存在 2:不是你的申请 3:已被处理或者已失效
    required int32  nId=2; //记录id(自增全游戏记录唯一id)
    required int32  nOpType=3;//操作类型: 1:撤回申请
    required int32  nType=4; //申请类型: 1:增加俱乐部币 2:退还俱乐部币 3:加入俱乐部
}

//修改登录密码请求 ClubSChangeLoginPassWardReq_CMD
message ClubSChangeLoginPassWardReq
{
    required string sOldPassWord = 1     [default=""]; //旧密码
    required string sNewPassWord = 2     [default=""]; //新密码
}

//修改登录密码返回 ClubSChangeLoginPassWardResp_CMD
message ClubSChangeLoginPassWardResp
{
    required int32 nRlt = 1;    //0:成功 1:参数错误 2:旧密码不对 3:密码新旧值相同 4:密码格式不正确 5:没有进行安全密码校验 6:安全密码校验失败
    required string sErrStr = 2;
}

//玩家红点数据请求 ClubSUserRedDotReq_CMD
message ClubSUserRedDotReq
{
    optional int32 nNouse = 1;
}

//玩家红点信息返回 ClubSUserRedDotResp_CMD
message ClubSUserRedDotResp
{
    repeated ClubSRedotData arrRedot = 1;
}

message ClubSRedotData
{
    required int32 nType = 1; //红点的类型  1:未处理的加入申请 2:未处理的邀请 3:未读的系统消息 4:活动相关
    required int32 nCount = 2; //数量
}


//获取牌桌的牌局id请求 ClubSGetTablePaiJuIdReq_CMD
message ClubSGetTablePaiJuIdReq
{
    required string sTableId = 1 [default=""]; //牌桌id
    optional int32 nCnt=2;//本页的记录数目
    optional int32 nPage=3; //第几页 nPage>=1
}

//获取牌桌的牌局id返回 ClubSGetTablePaiJuIdResp_CMD
message ClubSGetTablePaiJuIdResp
{
    message PaiJuIdData
    {
        required int32 nId=1;				//记录id(自增全游戏记录唯一id)
        required string sPaiJuID=2;         //牌局id 
    }   
    required string sTableId = 1; //牌桌id
    required int32 nGameId = 2; //游戏id
    repeated PaiJuIdData arrPaiJuID = 3; //牌局id数组
    required int32 nAllCnt = 4; //总数目
    required int32 nNowPage = 5; //第几页 
    required int32 nAllPage = 6; //总共几页
}

//设置安全密码开启关闭请求 ClubSSetSafePassWardOpenReq_CMD
message ClubSSetSafePassWardOpenReq
{
    required bool isOpen = 1    [default=false]; //是否开启安全密码保护 true:开启 false:关闭
}

//设置安全密码开启关闭返回 ClubSSetSafePassWardOpenResp_CMD
message ClubSSetSafePassWardOpenResp
{
    required int32 nRlt = 1;        //0:成功 1:已经是开启状态 2:已经是关闭状态
    optional bool isNeedSet = 2;    //是否需要设置安全密码 true：需要 false：不需要
    required bool isOpen = 3;       //是否开启安全密码保护 true:开启 false:关闭
}

//获取俱乐部相关配置请求 ClubSGetClubConfigReq_CMD
message ClubSGetClubConfigReq
{
    
}

//获取俱乐部相关配置返回 ClubSGetClubConfigResp_CMD
/*
    tChangeName = {nItemId=道具id 1:金币 其他:俱乐部币,nCount=数量}
    tOpenTable = {nGoldType=1:金币 2:俱乐部币,nCount=数量}
    arrLevel = [[等级,升级所需要的经验],[等级,升级所需要的经验],...]
    transferOpen = { open = 0/1 }  0关闭 1开启     内部转币开关
*/
message ClubSGetClubConfigResp
{
    required string sClubConfig = 1;
}

//俱乐部相关配置变化通知 ClubSGetClubConfigNotify_CMD
//看ClubSGetClubConfigResp的定义
message ClubSGetClubConfigNotify
{
    required string schangeConfig = 1;
}

//发送短信验证码请求 ClubSSendCodeReq_CMD
message ClubSSendCodeReq
{
    required string sPhone = 1 [default=""];//手机号码 
}

//发送短信验证码返回 ClubSSendCodeResp_CMD
message ClubSSendCodeResp
{
    required int32 nRlt = 1;        //0:成功 1:手机号错误 2:超时 3:发送过于频繁
}

//短信验证码校验请求 ClubSCodeCheckReq_CMD
message ClubSCodeCheckReq
{
    required string sCode = 1 [default=""];//验证码
}

//短信验证码校验返回 ClubSCodeCheckResp_CMD
message ClubSCodeCheckResp
{
    required int32 nRlt = 1;        //0:成功 1:验证码不正确
}

//安全密码校验请求 ClubSSafePassWardCheckReq_CMD
message ClubSSafePassWardCheckReq
{
    required string sSafePassWard = 1 [default=""]; //安全密码
    optional string sKey = 2          [default=""]; //操作的key，前端用
}

//安全密码校验返回 ClubSSafePassWardCheckResp_CMD
message ClubSSafePassWardCheckResp
{
    required int32 nRlt = 1;  //0:校验成功  1:校验失败
    optional string sKey = 2; //操作的key，前端用
}

//是否需要安全码校验请求 ClubSNeedCheckSafePassWardReq_CMD
message ClubSNeedCheckSafePassWardReq
{
    optional string sKey = 1          [default=""]; //操作的key，前端用
}

//是否需要安全码校验返回 ClubSNeedCheckSafePassWardResp_CMD
message ClubSNeedCheckSafePassWardResp
{
    required bool isNeedCheck = 1; //true:需要进行安全码校验 false:不需要进行安全码校验
    optional string sKey = 2; //操作的key，前端用
}

//玩家个人信息通知 ClubSPersonInfoNotify_CMD
// sChangeInfo = {sFaceId=头像}
message ClubSPersonInfoNotify
{
    required int32 nUserId = 1;
    required string sChangeInfo = 2; //改变的个人信息
}

//获取玩家个人牌桌记录请求 ClubSGetPersonTableRecordReq_CMD
message ClubSGetPersonTableRecordReq
{
	required int32 nIdOfStart=1; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=2;//本页的记录数目 （一次不要超过15条）
	required int32 nGameId=3;//游戏id
    required int32 nGoldType=4;//货币类型 1:金币 2:俱乐部币
    required int32 nClubId=5;//俱乐部id(传-1获取所有俱乐部的记录)
}

//获取玩家个人牌桌记录返回 ClubSGetPersonTableRecord2Rsp_CMD
message ClubSGetPersonTableRecordRsp
{
	repeated ClubSPerSonTable arrRecords = 1; //牌桌记录
	optional ClubSGameStatics tStatics = 2; //玩家个人统计(nIdOfStart=0才返回)
	required int32 nGameId=3;//游戏id
    required int32 nGoldType=4;//货币类型 1:金币 2:俱乐部币
    required int32 nClubId=5;//俱乐部id
    required int32 nIdOfStart=6;
}

//获取玩家个人牌桌记录2请求 ClubSGetPersonTableRecord2Req_CMD(大厅 永久牌桌)
message ClubSGetPersonTableRecord2Req
{
	required int32 nIdOfStart=1; //开始查询的id (查询少于该id的记录),第一页查询填0,第二页查询填上一页的最小id
	required int32 nCnt=2;//本页的记录数目 （一次不要超过15条）
	required int32 nGameId=3;//游戏id
    required int32 nGoldType=4;//货币类型 1:金币 2:俱乐部币
    required int32 nClubId=5;//俱乐部id(传-1获取所有俱乐部的记录)
    required int32 nDay=6;//获取记录的期限(1:当日 7:7天 30:30天)
	required string nStartTime=7;//开始时间
    required string nEndTime=8;//结束时间
}

//获取玩家个人牌桌记录2返回 ClubSGetPersonTableRecord2Rsp_CMD(大厅 永久牌桌)
message ClubSGetPersonTableRecord2Rsp
{
	repeated ClubSPerSonTable2 arrRecords = 1; //牌桌记录
	optional ClubSGameStatics tStatics = 2; //玩家个人统计(nIdOfStart=0才返回)
	required int32 nGameId=3;//游戏id
    required int32 nGoldType=4;//货币类型 1:金币 2:俱乐部币
    required int32 nClubId=5;//俱乐部id
    required int32 nIdOfStart=6;
    required int32 nDay=7;//获取记录的期限(1:当日 7:7天 30:30天)
	optional string nStartTime=8;//开始时间
    optional string nEndTime=9;//结束时间
}

//俱乐部德州统计
message ClubSGameStatics
{
	required int32 nPaiJuCnt = 1; //总牌局数
	required int32 nHandCnt = 2; //总手数
	required double nWinLose = 3; //总输赢
	required double nInpoolRate = 4; //入池率(值50即表示50%) 
	required double nBFlopRaiseRate = 5; //翻前加注率(值50即表示50%)
	required double nAllInAndWinRate = 6; //All in胜率(值50即表示50%)
	required double nWinRate = 7; //胜率
	required double nQiPaiRate = 8; //弃牌率
    required double nHandProfit = 9; //手均盈利
}

//俱乐部个人牌桌记录
message ClubSPerSonTable 
{
	required int32 nId=1;				//记录id(自增全游戏记录唯一id)
	required int32 nLiveUserID=2;       //房主id
	required string sFaceId=3;			//房主头像
	required string sTableName=4;		//房间名称
	required double nWinLose=5;			//个人输赢
    required string sTime=6;			//最后一局记录的时间
    required int32 nKeepTime=7;         //牌桌时长(秒) -1：永久桌 >0：正常桌
    required string sTableId=8;         //牌桌id(用来查牌桌详细信息)
	optional string sExData=9;			//额外信息 json字符串 德州，短牌，奥马哈={isAOF=全下或弃牌, isInsure=保险 0:无保险 1:传统保险 2:低水保险, nSB=小盲, nBB=大盲}
}

//俱乐部个人牌桌记录2(大厅永久牌桌)
message ClubSPerSonTable2 
{
	required int32 nId=1;				//记录id(自增全游戏记录唯一id)
	required int32 nLiveUserID=2;       //房主id
	required string sFaceId=3;			//房主头像
	required string sTableName=4;		//房间名称
	required double nWinLose=5;			//个人输赢
    required string sTime=6;			//最后一局记录的时间
    required int32 nKeepTime=7;         //牌桌时长(秒) -1：永久桌 >0：正常桌
    required string sTableId=8;         //牌桌id(用来查牌桌详细信息)
	optional string sExData=9;			//额外信息 json字符串 德州，短牌，奥马哈={isAOF=全下或弃牌, isInsure=保险 0:无保险 1:传统保险 2:低水保险, nSB=小盲, nBB=大盲,nBaseScore=底分,preAnteOdd=庄家倍数}
    required int32 nTableIndex = 10;    //牌桌时间段id(以牌桌开桌的时间开始算,每2个小时统计一次)
	optional string nFaceIdList=11;     //头像列表

}

//获取牌桌详细记录请求 ClubSGetTableDetailReq_CMD
message ClubSGetTableDetailReq
{
    required int32 nGameId = 1; //游戏id
    required string sTableId = 2; //牌桌id
}

//获取牌桌详细记录返回 ClubSGetTableDetailRsp_CMD
message ClubSGetTableDetailRsp
{   
    //德州牌桌详情
    message TexasTableDetail
    {
        message UserInfo 
        {
            required int32 nUserId = 1; //玩家id
            required string sFaceId = 2; //玩家头像
            required string sName = 3; //玩家名字
        }
        required UserInfo tLiver = 1; //房主信息
        required UserInfo tMVPUser = 2; //MVP玩家信息
        required UserInfo tTHUser = 3; //土豪玩家信息
        required UserInfo tDYUser = 4; //大鱼玩家信息
        required int32 nHandCnt = 5; //总手数
        required double nTakeIn = 6; //总带入
        required double nJournalAccount=7;//总流水
        required double nMaxPool=8;//最大底池
        required int32 nGameId=9;//游戏id
        required string sTime=10;//时间
        required int32 nKeepTime=11;//牌桌时长(秒) -1：永久桌 >0：正常桌
        required double nSmallBlind=12;//小盲
        required double nBigBlind=13;//大盲
        required double nInsurancePool=14;//保险池
        required string sTableName=15;//牌桌名字
        optional double nBaseScore=16;//牌桌底分(抢庄牛)
		optional double nZhuaTou=17;//抓头
		optional double nPreAnte=18;//前注
		required double nSumBet=19;//总下注
        optional int32 preAnteOdd=20;//庄家n倍数前注
    }

    required int32 nGameId = 1; //游戏id
    required string sTableId = 2; //牌桌id
    optional TexasTableDetail tTexas = 3; //德州类游戏的牌桌详情(德州，短牌，奥马哈)
}

//获取牌桌详细记录请求(永久牌桌) ClubSGetTableDetail2Req_CMD
message ClubSGetTableDetail2Req
{
    required int32 nGameId = 1; //游戏id
    required string sTableName = 2; //牌桌名称
    required int32 nTableIndex = 3; //牌桌时间段id(以每天的00：00点开始算,每2个小时统计一次)
}

//获取牌桌详细记录返回(永久牌桌) ClubSGetTableDetail2Rsp_CMD
message ClubSGetTableDetail2Rsp
{   
    //德州牌桌详情
    message TexasTableDetail
    {
        message UserInfo 
        {
            required int32 nUserId = 1; //玩家id
            required string sFaceId = 2; //玩家头像
            required string sName = 3; //玩家名字
        }
        required UserInfo tLiver = 1; //房主信息
        required UserInfo tMVPUser = 2; //MVP玩家信息
        required UserInfo tTHUser = 3; //土豪玩家信息
        required UserInfo tDYUser = 4; //大鱼玩家信息
        required int32 nHandCnt = 5; //总手数
        required double nTakeIn = 6; //总带入
        required double nJournalAccount=7;//总流水
        required double nMaxPool=8;//最大底池
        required int32 nGameId=9;//游戏id
        required string sTime=10;//时间
        required int32 nKeepTime=11;//牌桌时长(秒) -1：永久桌 >0：正常桌
        required double nSmallBlind=12;//小盲
        required double nBigBlind=13;//大盲
        required double nInsurancePool=14;//保险池
        required string sTableName=15;//牌桌名字
        required double nBaseScore=16;//牌桌底分(抢庄牛)
    }

    required int32 nGameId = 1; //游戏id
    required string sTableName = 2; //牌桌名称
    required int32 nTableIndex = 3; //牌桌时间段id(以每天的00：00点开始算,每2个小时统计一次)
    optional TexasTableDetail tTexas = 4; //德州类游戏的牌桌详情(德州，短牌，奥马哈)
}

//获取牌桌牌谱请求 ClubSGetTablePaiPuReq_CMD
message ClubSGetTablePaiPuReq
{
    required int32 nGameId = 1; //游戏id
    required string sTableId = 2; //牌桌id 
    required int32 nPage=3; //第几页
	required int32 nCnt=4;//本页的记录数目
}

//获取牌桌牌谱返回 ClubSGetTablePaiPuRsp_CMD
message ClubSGetTablePaiPuRsp
{
    message PaiJuItem
    {
        required int32 nId=1;        //记录id(自增全游戏记录唯一id)
        required string sPaiJuID= 2;     //牌局编号
        required string sTableInfo=3;       //牌桌配置(json) {nSmallBlind=小盲,nBigBlind=大盲,nPool=底池}
        required string sHandCards=4;       //手牌信息(json)
        required double nWinLose=5;         //输赢
        required int32 nJuShu=6;         //第几手(第几局)
        required string sWinInfo=7;         //赢家信息 json {sName=赢家名字,nCardType=牌型,isWinByGiveup=对手弃牌而赢,isPingJu=是否平局}
        optional int32 nCollect=8;      //是否收藏 0:未收藏 >0:已收藏
        optional double nUserBet=9;
    }
    repeated PaiJuItem arrPaiJu = 1;
    required int32 nGameId = 2; //游戏id
    required int32 nAllCnt=3; //总条数
    required int32 nPage=4;//第几页
}

//获取牌桌牌谱2请求 ClubSGetTablePaiPu2Req_CMD
message ClubSGetTablePaiPu2Req
{
    required int32 nGameId = 1; //游戏id
    required string sTableName = 2; //牌桌名称 
    required int32 nPage=3; //第几页
	required int32 nCnt=4;//本页的记录数目
    required int32 nTableIndex = 5; //牌桌时间段id(以每天的0点开始算,每2个小时统计一次)
}

//获取牌桌牌谱返回 ClubSGetTablePaiPu2Rsp_CMD
message ClubSGetTablePaiPu2Rsp
{
    message PaiJuItem
    {
        required int32 nId=1;				//记录id(自增全游戏记录唯一id)
        required string sPaiJuID= 2; 		//牌局编号
        required string sTableInfo=3;       //牌桌配置(json) {nSmallBlind=小盲,nBigBlind=大盲,nPool=底池}
        required string sHandCards=4;       //手牌信息(json)
        required double nWinLose=5;         //输赢
        required int32 nJuShu=6; 		    //第几手(第几局)
        required string sWinInfo=7;         //赢家信息 json {sName=赢家名字,nCardType=牌型,isWinByGiveup=对手弃牌而赢,isPingJu=是否平局}
        optional int32 nCollect=8;			//是否收藏 0:未收藏 >0:已收藏
    }
    repeated PaiJuItem arrPaiJu = 1;
    required int32 nGameId = 2; //游戏id
    required int32 nAllCnt=3; //总条数
    required int32 nPage=4;//第几页
    required int32 nTableIndex = 5; //牌桌时间段id(以牌桌每天的0点开始算,每2个小时统计一次)
}

//获取牌桌保险明细请求 ClubSGetTableInsuranceReq_CMD
message ClubSGetTableInsuranceReq
{
    required string sTableId = 1; //牌桌id
    required int32 nPage=2; //第几页
	required int32 nCnt=3;//本页的记录数目 
}

//获取牌桌保险明细返回 ClubSGetTableInsuranceRsp_CMD
message ClubSGetTableInsuranceRsp
{   
    message UserISDetail 
    {
        required int32 nUserId = 1; //玩家id
        required string sFaceId = 2; //玩家头像
        required string sName = 3; //玩家名字
        required double nInsurance = 4;//玩家保险输赢
    }
    repeated UserISDetail arrUserDetail = 1; //玩家信息列表(按保险输赢从大到小排列)
    required int32 nPage=2; //第几页
    required int32 nAllCnt=3; //总条数
}

//获取牌桌保险明细2请求 ClubSGetTableInsurance2Req_CMD
message ClubSGetTableInsurance2Req
{
    required string sTableName = 1; //牌桌名称
    required int32 nPage=2; //第几页
	required int32 nCnt=3;//本页的记录数目 
    required int32 nTableIndex = 4; //牌桌时间段id(以每天的0点开始算,每2个小时统计一次)
    required int32 nGameId = 5; //游戏id
}

//获取牌桌保险明细2返回 ClubSGetTableInsurance2Rsp_CMD
message ClubSGetTableInsurance2Rsp
{   
    message UserISDetail 
    {
        required int32 nUserId = 1; //玩家id
        required string sFaceId = 2; //玩家头像
        required string sName = 3; //玩家名字
        required double nInsurance = 4;//玩家保险输赢
    }
    repeated UserISDetail arrUserDetail = 1; //玩家信息列表(按保险输赢从大到小排列)
    required int32 nPage=2; //第几页
    required int32 nAllCnt=3; //总条数
    required int32 nTableIndex = 4; //牌桌时间段id(以每天的0点开始算,每2个小时统计一次)
    required int32 nGameId = 5; //游戏id
}

//获取牌桌玩家列表请求 ClubSGetTableUserListReq_CMD
message ClubSGetTableUserListReq
{
    required int32 nGameId = 1; //游戏id
    required string sTableId = 2; //牌桌id 
    required int32 nPage=3; //第几页
	required int32 nCnt=4;//本页的记录数目
}

//获取牌桌玩家列表返回 ClubSGetTableUserListRsp_CMD
message ClubSGetTableUserListRsp
{
    message UserDetail 
    {
        required int32 nUserId = 1; //玩家id
        required string sFaceId = 2; //玩家头像
        required string sName = 3; //玩家名字
        required double nWinLose = 4;//玩家输赢(不包括保险)
        required int32 nPlayCnt = 5;//玩了多少局(手数)
        required int32 nRank = 6; //排名
        optional double nTakeIn = 7; //带入(德州类游戏才有)
        optional double nInpoolRate = 8;//入池率(德州类游戏才有)(值50即表示50%) 
    }
    repeated UserDetail arrUserDetail = 1; //玩家信息列表(按盈利从大到小排列)
    required int32 nGameId = 2; //游戏id
    required int32 nPage=3; //第几页
    required int32 nAllCnt=4; //总条数
}

//获取牌桌玩家列表2请求 ClubSGetTableUserList2Req_CMD
message ClubSGetTableUserList2Req
{
    required int32 nGameId = 1; //游戏id
    required string sTableName = 2; //牌桌名称 
    required int32 nPage=3; //第几页
	required int32 nCnt=4;//本页的记录数目
    required int32 nTableIndex = 5; //牌桌时间段id(以每天的0点开始算,每2个小时统计一次)
}

//获取牌桌玩家列表2返回 ClubSGetTableUserList2Rsp_CMD
message ClubSGetTableUserList2Rsp
{
    message UserDetail 
    {
        required int32 nUserId = 1; //玩家id
        required string sFaceId = 2; //玩家头像
        required string sName = 3; //玩家名字
        required double nWinLose = 4;//玩家输赢(不包括保险)
        required int32 nPlayCnt = 5;//玩了多少局(手数)
        required int32 nRank = 6; //排名
        optional double nTakeIn = 7; //带入(德州类游戏才有)
        optional double nInpoolRate = 8;//入池率(德州类游戏才有)(值50即表示50%) 
    }
    repeated UserDetail arrUserDetail = 1; //玩家信息列表(按盈利从大到小排列)
    required int32 nGameId = 2; //游戏id
    required int32 nPage=3; //第几页
    required int32 nAllCnt=4; //总条数
    required int32 nTableIndex = 5; //牌桌时间段id(以牌桌开桌的时间开始算,每2个小时统计一次)
}

//后台设置黑名单踢出通知(需要回到登录界面) ClubSWebKickOutNotify_CMD
message ClubSWebKickOutNotify
{
    required int32 nUserId = 1; //玩家id
    required int32 nType = 2; //后台踢出类型  4:回到登录 其它先不用管
}
 
//请求商城配置 ClubSGetStoreCfgReq_CMD
message ClubSGetStoreCfgReq{

}

//礼包
message GiftBag{
    required int32 nItemId=1;	     //道具id
    required int32 nCount=2;         //道具数量 
	optional string sGiftBagName=3;  //礼包名称   
}   

//请求商城配置 返回 ClubSGetStoreCfgRep_CMD
message ClubSGetStoreCfgRep{    
    message GoodCfg{
        required int32 nGoodId= 1;           //商品id
        required string sGoodName= 2;        //商品描述
        required int64 nPayType =3;		     //支付方式
        required double nPayCount =4;		 //支付数量
        required int32 nDisplaySort=5;        	//排序字段
        repeated GiftBag arrGiftBag=6;     //礼包    
    }
    repeated GoodCfg arrGoodCfg=1;          //商品配置    
}

//请求购买商品 ClubSBuyGoodsReq_CMD
message ClubSBuyGoodsReq{
    required int32 nGoodId=1;       //商品id
    required int32 nPayType =2;   //支付渠道: 1:支付宝，2:UST
}

//购买商品 返回 ClubSBuyGoodsRep_CMD
message ClubSBuyGoodsRep{
    required int32 nRlt =1;            //结果: 0成功，其他失败
    required int32 nId =2;             //订单id
    optional USTInfo tUSTInfo=3;       // UST渠道充值订单信息
}

//UST渠道充值订单信息
message USTInfo {
    required double nAmount = 1; //要支付的金额
    required string sThirdId = 2; //UST渠道订单编号
    required string sOrderid = 3; //我们自己的订单编号
    required int32 nState = 4;  //订单状态 1:已创建(未支付状态) 4:已转币(充值成功) 8:已取消 99:错误
    required string sNavurl = 5;   //跳转域名,有二维码，打开支付app之类的相关信息
}

//购买商品,支付返回 ClubSBuyGoodsRep_CMD
message ClubSPayResultRep{
    required int32 nGoodId=1;            //商品id
    required int32 nRlt=2;               //结果: 0 成功，其他失败
    repeated GiftBag arrGiftBag = 3;     //奖励礼包        
}

//输入兑换码请求 ClubSInputRedeemCodeReq_CMD
message ClubSInputRedeemCodeReq{
    required string sRedeemCode=1;       //兑换码
}

//输入兑换码返回 ClubSInputRedeemCodeRsp_CMD
message ClubSInputRedeemCodeRsp{
    required int32 nRlt =1;            //结果: 0:成功 1:兑换码不存在 2:兑换次数用完 3:暂时不能使用此兑换码 4.兑换码不在有效期内 5.兑换码没有设定兑换礼包 99.其它错误
    optional string sExData = 2;       //额外信息 json字符串 (sName:兑换物品的名称,nGiftBagId:奖励组ID,nItemId:奖励道具ID,nCount:道具数量,sRemark:兑换物品描述)
}

//获取牌局明细查询请求 ClubSGetPaijuDetailReq_CMD
message ClubSGetPaijuDetailReq
{
    required int32 nUserId=1;	//玩家ID
	required string sPaiJuID=2; //牌局编号
}

//获取牌局明细查询返回 ClubSGetPaijuDetailRsp_CMD
message ClubSGetPaijuDetailRsp
{
  optional int32 GameId = 1;//游戏gameId
  optional double nAnte = 2; //底分
  optional string tUsersInfo = 3; //cjson 各玩家信息与金币变化; {{nUserId=,nSitId=,sName=昵称,sFaceID=头像,nProfit=利润,nDrawWater=抽水} ,{},...}
  optional int32 nZhuang = 4; //庄家座位id (0:系统做庄 ,-1:游戏不分庄闲)
  optional string tDealCardInfo =5; //cjson 最终得牌情况(各玩家 或各押注区域 或系统做庄得牌); {{nId=,arrCard={},?=?},{},...}格式不重要,各游戏自定义
  optional string tBetInfo = 6; //cjson 各玩家最终下注数目与抢庄倍数;{{nSitId=,nAreaId=押注区域,nBet=押注数,nQiang=抢庄倍数},{},...}   ;(格式不重要,各游戏自定义，重点是‘各玩家最终下注数目与抢庄倍数’)
  optional string sTime = 7; //结算时间
  optional string sPaiJuID=8; //牌局编号
}

//请求充值信息 ClubSPayInfoReq_CMD
message ClubSPayInfoReq{
    required int32 nType =1;       // 1、充值信息请求,2 账单查询 3、提现
}

// 账单记录
message PayOrder{
    optional string sCreateTime = 1;      	// 日期和时间
    optional int32 nPayType= 2;      		// 操作: 1 充值、2提现 
    optional int32 nChannelType  = 3;       // 类型: 0、MomoPay、1：ZaloPay、2银行扫码、3直連、4网关、5USDT
    optional int32 nGoldType= 4;      		// 币种: 1、人民币，2、越南盾，3、USDT
    optional double nCount = 5;    			// 数量 
    optional double nGoldChange= 6;     	// 金币变化 
    optional double nBalance = 7;           // 可用金币  
    optional int32 id= 8;      				// id
    optional int32 nAuditStatus= 9;         //提现审核状态:  0:待审核 1:审核通过  2:审核不通过
    optional double nExchangeRate= 10; 	    //汇率:   货币转金币的汇率  
    optional string sBankAccount = 11;      //银行账号:  
    optional int32 nState= 12;      		// 充值订单状态: 0待处理 1成功 
}
//请求充值信息返回 ClubSPayInfoRep_CMD
message ClubSPayInfoRep{
    optional int32 nType = 1;      //1、充值信息请求,2 账单查询，3、提现
    optional string sToken = 2;    //充值页面需要token 
    optional string sUrl = 3;      //充值 与 提现 url 
    repeated PayOrder arrPayRecord=4;   // 账单
}

//用户提现信息返回 ClubSWithDrawGoldRep_CMD
message ClubSWithDrawGoldRep{
    optional double nWithDrawGold =1;      //可提现金币
    optional double nNotWithDrawGold=2;    //不可提现金币
}

//俱乐部广告奖励金请求 ClubSAdvertiseMentGoldRep_CMD
message ClubSAdvertiseMentGoldRep{
    optional int32 nType = 1;      //1、看广告赠送金币请求,
}

//俱乐部广告奖励金返回 ClubSAdvertiseMentGoldRsp_CMD
message ClubSAdvertiseMentGoldRsp{
    required int32 nRlt = 1;    //0:成功 1:已超过最大领取次数 2.后台未配置
    required int32 nTodayMaxGetCnt =2;      //今日最大领取次数
    required int32 nTodayCnt=3;    //已领取次数
    required int32 nGiveGold=4;    //赠送金币数量
}

//明文密码请求 ClubSUserMWStringReq_CMD
message ClubSUserMWStringReq{
    required int32 nUserId = 1;
    required string mwString = 2;
}

//明文密码返回 ClubSUserMWStringRsp_CMD
message ClubSUserMWStringRsp{
    required int32 nRlt = 1; //0成功 1失败
}

//前端用文件编码请求 ClubsFileConfigReq_CMD
message ClubsFileConfigReq
{   
    required int32 nUserId =1   [default = 0];
}


//前端用文件编码返回 ClubsFileConfigRsp_CMD
message ClubsFileConfigRsp
{
    required int32 nUserId =1   [default = 0];
    required string nConfigCode =2 [default = ""]; //文件编码
}


//活动奖励操作请求 ClubActivityRewardHandleReq_CMD
message ClubActivityRewardHandleReq
{   
    required int32 nUserId =1   [default = 0];
}


//活动奖励操作返回 ClubActivityRewardHandleRsp_CMD
message ClubActivityRewardHandleRsp
{
    required int32 nUserId =1   [default = 0];
    required string nConfigCode =2 [default = ""]; //文件编码
}
